### ISSUE TITLE
Error while installation

### ISSUE THREAD

**Issue by averagegnomedeenjoyer** [notthebee/ansible-easy-vpn#1]
I have a problem with the installation of the script. When i run the script everything is alright, until i run the playbook. After some time this massage appears in my terminal 

fatal: [localhost]: FAILED! => changed=false 
  msg: Failed to import the required Python library (cryptography >= 3.0) on localhost's Python /usr/bin/python3. This is required to load/dump private keys in the default OpenSSH format for OpenSSH >= 7.8 or for ed25519 keys. Please read the module documentation and install it in the appropriate location. If the required library is installed, but Ansible is using the wrong Python interpreter, please consult the documentation on ansible_python_interpreter

OS: Ubuntu Server 20.04 LTS

**Comment by notthebee** [comment]
Normally, cryptography should be installed by the playbook and I've tested it on 20.04
Try installing it manually and re-running the playbook:

```
pip3 install cryptography
cd $HOME/ansible-easy-vpn && ansible-playbook run.yml
```

**Comment by notthebee** [comment]
Just found the error. Should be fixed now

**Comment by averagegnomedeenjoyer** [comment]
Alright, thank you!
