### ISSUE TITLE
Error: ''/usr/bin/aptitude safe-upgrade'' failed

### ISSUE THREAD

**Issue by AhmedHemdan21** [notthebee/ansible-easy-vpn#104]
Hello, 

Whenever I try to run the script it throws '/usr/bin/aptitude safe-upgrade' and it doesn't complete.

System Information

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal

Hosted on Azure.
PLAY [all] *************************************************************************************************************

TASK [Gathering Facts] *************************************************************************************************
ok: [localhost]

TASK [set_fact] ********************************************************************************************************
ok: [localhost]

TASK [system : Configure the system] ***********************************************************************************
included: /home/{username}/ansible-easy-vpn/roles/system/tasks/essential.yml for localhost

TASK [system : Generate the locale] ************************************************************************************
ok: [localhost]

TASK [system : Update and upgrade apt packages] ************************************************************************

fatal: [localhost]: FAILED! => changed=false
  msg: '''/usr/bin/aptitude safe-upgrade'' failed: '
  rc: -9
  stdout: |-
    Reading package lists...
    Building dependency tree...
    Reading state information...
    Reading extended state information...
    Initializing package states...
    Writing extended state information...
    Building tag database...
  stdout_lines: <omitted>

PLAY RECAP *************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by notthebee** [comment]
Can you execute the following lines manually and post the output here?
```
sudo apt update
sudo apt upgrade
```
Feel free to omit `sudo` if you're already running as root

**Comment by AhmedHemdan21** [comment]
![image](https://user-images.githubusercontent.com/7311025/205460649-52d90cbc-f7b7-432a-a095-b9146e1d6a19.png)
it works fine, I've tried with 2 servers since yesterday, the first was ubuntu 22.04 and the current one is ubuntu 20.04 and both have the exact same issue

**Comment by notthebee** [comment]
`sudo apt autoremove` also works fine if you execute it manually?

**Comment by davjet1** [comment]
I am having this same exact issue. apt update and and upgrade show no available updates and I have rerun the script multiple times, even completely reinstalling ubuntu server. 
<img width="825" alt="image" src="https://user-images.githubusercontent.com/38332550/209482236-6dd150ec-fe43-46f2-af6d-6f793c7a9f5e.png">

**Comment by notthebee** [comment]
> I am having this same exact issue. apt update and and upgrade show no available updates and I have rerun the script multiple times, even completely reinstalling ubuntu server. <img alt="image" width="825" src="https://user-images.githubusercontent.com/38332550/209482236-6dd150ec-fe43-46f2-af6d-6f793c7a9f5e.png">

Are you also on Azure?

**Comment by davjet1** [comment]
No, but I think it has something to do with my installation of Ubuntu 20.04. The install provided by the VPS I was using must have been faulty since when I tried again using my own install of Ubuntu 20.04 it worked. I am using VirMach.

**Comment by notthebee** [comment]
This seems to be related to Ubuntu images used by some VPS providers. For instance, AlexHost runs `apt dist-upgrade` on their Ubuntu instances right after deployment, which might interfere with the playbook. Not sure about Azure.

Unfortunately, I can't test the script on every VPS in existence, so more information from people who experience the issue would be amazing.

**Comment by notthebee** [comment]
Closing due to no feedback
