### ISSUE TITLE
How do i recreate 2fa

### ISSUE THREAD

**Issue by keenops** [notthebee/ansible-easy-vpn#105]
I followed the steps in the youtube video [here](https://www.youtube.com/watch?v=SMF301vQqJo&ab_channel=Wolfgang%27sChannel) to set up a VPN. Everything was good ad set. But now I have lost the device with an authenticator. Tring the command `show_2fa` I get an error `Failed to register device, the provided link is expired or has already been used`. How do I login back to wg

**Comment by notthebee** [comment]
Do the following:
```
docker stop aufgelistet
sudo rm -rf /opt/docker/authelia
cd ~/ansible-easy-vpn
ansible-galaxy install -r requirements.yml
ansible-playbook run.yml -K --tags authelia
```

**Comment by keenops** [comment]
thanks!

**Comment by codercodingthecode** [comment]
ansible-playbook run.yml -K --tags authelia
BECOME password:
ERROR! Attempting to decrypt but no vault secrets found

the password I have previously set, does not work.

**Comment by stankovicst** [comment]
I got the same error.:

ansible-playbook run.yml -K --tags authelia
BECOME password:
ERROR! Attempting to decrypt but no vault secrets found

Is there a solution
