### ISSUE TITLE
backup

### ISSUE THREAD

**Issue by dynimighti** [notthebee/ansible-easy-vpn#108]
what files should be backed up?

**Comment by notthebee** [comment]
/opt/docker

**Comment by arsaces7** [comment]
> /opt/docker

after running scrip i only can access the vps with user that i made and not the root , and user don't have the permission to backup those files , how can i backup them?

**Comment by notthebee** [comment]
```
sudo cp -rv /opt/docker ~/opt_docker_backup
scp username@server-ip:~/opt_docker_backup opt_docker_backup
```

**Comment by arsaces7** [comment]
> ```
> sudo cp -rv /opt/docker ~/opt_docker_backup
> scp username@server-ip:~/opt_docker_backup opt_docker_backup
> ```

thank you for answering i get this

[scp username@server-ip:~/opt_docker_backup opt_docker_backup](scp: /home/user/opt_docker_backup: not a regular file)

**Comment by notthebee** [comment]
Yep, sorry, should've been `scp -r`. If not, `scp -ar`.

**Comment by arsaces7** [comment]
> Yep, sorry, should've been `scp -r`. If not, `scp -ar`.

scpr -r : opt_docker_backup/opt_docker_backup: Permission denied
scp -ar : unknown option -- a
usage: scp [-346BCpqrTv] [-c cipher] [-F ssh_config] [-i identity_file]
            [-J destination] [-l limit] [-o ssh_option] [-P port]
            [-S program] source ... target

**Comment by notthebee** [comment]
Go back to the server and do `sudo chown -R username:username ~/opt_docker_backup`
Then try the `scp -r` command again

**Comment by arsaces7** [comment]
> Go back to the server and do `sudo chown -R username:username ~/opt_docker_backup` Then try the `scp -r` command again

opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/opt_docker_backup/bunkerweb/data/letsencrypt/accounts/acme-v02.api.letsencrypt.org/directory/c2c9edab33bb2b339f0395da0c0fafb7/private_key.json: Permission denied
regr.json                                                                                                                                                    0%    0     0.0KB/s   --:-- ETABroken pipe


is it possbile to change the permission of that folder and access it with sftp?

**Comment by notthebee** [comment]
It is – there are plenty of tutorials online on how to use `chmod` and chown`.
This looks like you've somehow created an infinite number of directories inside directories :D Not sure how that's possible.

**Comment by arsaces7** [comment]
me neither )) i just copied what you said - how can i detele them?

**Comment by arsaces7** [comment]
> It is – there are plenty of tutorials online on how to use `chmod` and `chown`. This looks like you've somehow created an infinite number of directories inside directories :D Not sure how that's possible.

at the end i managed to backup all the files with sftp except fullchain.pem , chain.pem ... (pem ,files)
