### ISSUE TITLE
Vault format error

### ISSUE THREAD

**Issue by TheFirstMonster** [notthebee/ansible-easy-vpn#11]
`
[WARNING]:
There was a vault format error in /root/ansible-easy-vpn/secret.yml: Vault format unhexlify error: Odd-length string
ERROR! Vault format unhexlify error: Odd-length string
`

Maybe because there are special characters in the password. It complained about "Character . sequence" or something like that on vault creation before.

**Comment by notthebee** [comment]
Run `file secret.yml`
Does it say "secret.yml: ASCII text, with CRLF line terminators"?

**Comment by TheFirstMonster** [comment]
> Run `file secret.yml` Does it say "secret.yml: ASCII text, with CRLF line terminators"?

```
file secret.yml
secret.yml: ASCII text, with escape sequences
```

**Comment by notthebee** [comment]
That's weird. I will re-test it with special characters in the password

**Comment by notthebee** [comment]
Just tried setting this as a password:
`" !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~"`
And it work. What special characters does your password include?

**Comment by TheFirstMonster** [comment]
So I retried with a vault password that has only letters and numbers and the creation of the vault worked.

Then I got this error:
```
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  did not find expected alphabetic or numeric character

The error appears to be in '/root/ansible-easy-vpn/secret.yml': line 1, column 20, but may
be elsewhere in the file depending on the exact syntax problem.
```
After that I tried also changing the user password with `ansible-vault edit secret.yml` to one without special characters and now it is working.

The previous vault password was XR3!;Y'`4ts5KG%R (i don't use it anymore so no problem)
But I guess there's something different in my environment although I am using a clean install Ubuntu 20.04.

**Comment by notthebee** [comment]
Hmm. Just tried creating a Vault file with your password on my machine, and it worked. I will close the issue for now, let's see if anyone else is able to reproduce it.

**Comment by nxvzft4olewmnd7ozgrktw** [comment]
I am able to reproduce this error with a complex vault password.

**Comment by nxvzft4olewmnd7ozgrktw** [comment]
A bit of debugging shows, in my case this is not about the vault or user password but the smtp password which is on line one of secret.yml. My smtp password was complex (included numbers and special characters) but as soon as I changed it to use alphanumeric characters only, so no special characters, things progress normally. The special character that seemed to trip up the parsing was a comma.
