### ISSUE TITLE
Connects to the server, but don't have access to internet

### ISSUE THREAD

**Issue by DoctorHoax** [notthebee/ansible-easy-vpn#111]
Hello there,
Thanks for the easy VPN packet, I've successfully installed it on my VPS and created a client.
It connects to the server just fine but the problem is I can't access the internet at all, what should I do? (I can't login to the root user either (Permission denied (publickey).))

**Comment by notthebee** [comment]
You shouldn't be able to connect via the root account after the playbook is finished. Please read the instructions at the end of the playbook carefully and make sure you've copied the public key from the VPS. If you did everything correctly, you should be able to login with your username and your new public key.

The ports can be customized by putting `wireguard_port: "your-port-here"` in the custom.yml file after running the bootstrap.sh script, but before running the playbook.

If you've already ran the playbook, you can re-run it after putting the variable in the `custom.yml` file

**Comment by davidtavarez** [comment]
for ionos.de you will need to configure the firewall.

thank you @notthebee this works very well.

**Comment by notthebee** [comment]
Closed due to inactivity. Feel free to re-open if the issue still persists
