### ISSUE TITLE
VPS WireGuard Connection Issue

### ISSUE THREAD

**Issue by memeorable** [notthebee/ansible-easy-vpn#112]
Wolf,
First off, amazing tool you created here! I used this to create a VPN on my Linode VPS for a few months now and it has worked flawlessly. Due to changing providers, I recently tried to set this up on a IONOS VPS with no luck. Everything seems to work fine until I try and connect to WireGuard. It allows me to create WireGuard clients, but when connecting to the client, there is no connection to the internet. Could this be an issue with the VPS provider? I have tried installing this twice now.

**Environment:**
- Client OS: Windows
- VPS OS Ubuntu 20.04
- VPS Provider IONOS

**Comment by notthebee** [comment]
As mentioned in this issue https://github.com/notthebee/ansible-easy-vpn/issues/68#issuecomment-1256911450, IONOS seems to feature its own firewall. Try opening the Wireguard port (51820) in IONOS' control panel and see if the issue persists

**Comment by memeorable** [comment]
This fixed the issue! Appreciate the help.
