### ISSUE TITLE
Install on Debian

### ISSUE THREAD

**Issue by Ahwxx** [notthebee/ansible-easy-vpn#12]
Hey,

Does the script work on Debian(-based) systems as well? I want to run this on my own server for accessing my own network from outside without having to spin up a Ubuntu VM (because of server resources).

Cheers!

**Comment by notthebee** [comment]
Hi,

The script has only been tested on Ubuntu. But I will definitely consider porting it to Debian

**Comment by Ahwxx** [comment]
Thanks for the quick reply! What ports do I need to open to use this on a home network? Just 51280?

**Comment by notthebee** [comment]
51820 for Wireguard, 80 and 443 for WebUI

**Comment by Ahwxx** [comment]
Ah okay, can I use different ports (already have NGINX reverse proxy set up)?

**Comment by notthebee** [comment]
You can, but this is untested and you will need to edit the playbook manually

**Comment by Ahwxx** [comment]
Alright! Thanks!
