### ISSUE TITLE
erorr with this task [TASK [dns : Copy the docker folder to /opt/docker]

### ISSUE THREAD

**Issue by bluedog20** [notthebee/ansible-easy-vpn#121]
- [X ] I've read the [FAQ](https://github.com/notthebee/ansible-easy-vpn/blob/main/FAQ.md) and my problem isn't described there.
- [ X] I've also searched through the existing issues, and my problem hasn't been brought up

**Describe the issue**
error with the playbook.  i ran the playbook multiple times.  brand new install of Ubuntu 20.04 from Racknerd VPS.

**Logs (if applicable)** 
Paste any relevant error messages here:
``
TASK [dns : Copy the docker folder to /opt/docker] *******************************************************************************************************************************************
fatal: [localhost]: FAILED! => changed=false 
  msg: 'Failed to find required executable "rsync" in paths: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'

**Environment:**
- Client OS: Linux Pop!_OS 22.04 LTS
- VPS OS [Ubuntu 20.04]
- VPS Provider [racknerd]

**Comment by notthebee** [comment]
Thanks for reporting it. I've fixed it in the last commit. This should fix your issue:
```
cd $HOME/ansible-easy-vpn
git pull
bash bootstrap.sh
```
