### ISSUE TITLE
Newbie question

### ISSUE THREAD

**Issue by RyanAngelos** [notthebee/ansible-easy-vpn#124]
Hi, bit of a silly one but is it possible to use this playbook on a Raspberry Pi or a Docker container? Provided that its running a compatible OS of course. In your video you only cover how to set this up as an "external" VPN but I'm looking to set up one for my office LAN.

Many thanks

**Comment by notthebee** [comment]
Yes, you can set this up on a Raspberry Pi, provided you can use port forwarding on your office LAN

**Comment by RyanAngelos** [comment]
Thanks!
