### ISSUE TITLE
scp command issue

### ISSUE THREAD

**Issue by Chinaboy5216** [notthebee/ansible-easy-vpn#13]
scp command end up in error

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ED255xx key sent by the remote host is
SHA256:f+eYH81SoDsuAgdbSfnkTAQQeYkdY0UH+axUzUvhuvg.
Please contact your system administrator.
Add correct host key in /home/xxxxxxxxx/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /home/xxxxxxxxx/.ssh/known_hosts:7
Host key for xxxxxxxxxxxx has changed and you have requested strict checking.
Host key verification failed.
scp: Connection closed

**Comment by notthebee** [comment]
This usually happens when you re-install the OS on your server
Open ~/.ssh/known_hosts on your host machine and delete the line(s) beginning with the IP of your server

**Comment by D3SOX** [comment]
> ```
> Offending ECDSA key in /home/xxxxxxxxx/.ssh/known_hosts:7
> ```

Just delete line 7 for example with GNU sed `sed -i '7d' $HOME/.ssh/known_hosts`
