### ISSUE TITLE
Cloudflare Universal SSL support

### ISSUE THREAD

**Issue by slowpokex** [notthebee/ansible-easy-vpn#130]
- [*] I've read the [FAQ](https://github.com/notthebee/ansible-easy-vpn/blob/main/FAQ.md) and my problem isn't described there.
- [*] I've also searched through the existing issues, and my problem hasn't been brought up

**Describe the issue**
Hello @notthebee 

First of all, I would like to thank you for the exceptionally great manual for VPN installation (https://www.youtube.com/watch?v=SMF301vQqJo), the setup was easy and everything works fine.

My environment is slightly different from yours and I have the following point - instead of using DuckDNS, I have my own domain name on Cloudflare. For more security, I tried to use proxying, but I have not succeeded so far.

The fact is that I had an error related to incorrect certificates (SSL_ERROR_NO_CYPHER_OVERLAP). And for this, I tried to change the generated letsencrypt's certificates to the certificates that I generated in Cloudflare, but it didn’t work out for me and therefore I temporarily disabled the Universal SSL function.

My question is, is there any way to substitute certificates for those that I have generated in Cloudflare so that I can enable request proxying and further limit the list of IP addresses on the VPS server (to Cloudflare specific)?

Thank you in advance

**Environment:**
- DNS Provider: Cloudflare
- VPS OS: Ubuntu 22.04
- VPS Provider: BlueVPS

**Comment by notthebee** [comment]
This is outside of the project scope for now, but I will revisit the issue once I have the time.
