### ISSUE TITLE
root@ipaddress: Permission denied (publickey). at the 

### ISSUE THREAD

**Issue by apexiptv** [notthebee/ansible-easy-vpn#132]
**Describe the issue**
Permission denied (publickey).

I'm getting this message no matter if I try to use root to sign into my vps through putty/terminal or any existing user credentials. 
When I did checked using vi sshd_config, the file has nothing in it.

It started doing this directly after this part of the tutorial video... 

![image](https://user-images.githubusercontent.com/42727116/215787382-2290e291-709b-45ef-a029-ead4d209d23f.png)

Almost done! Now you need to copy the private SSH key to your host machine
1. Open a new terminal window

2. Type the following commands:
cd
scp -P 22 root@ipaddress:/tmp/id_ssh_ed25519 .ssh/id_vpn_wgunix

It returned root@ipaddress Permission denied (publickey). 

The only access I have to my vps is through vnc commands.  

**Environment:**
- Client OS: [Linux]
- VPS OS [e.g. Ubuntu 22.04]
- VPS Provider [dedipath.com]

**Comment by slowpokex** [comment]
Hello @apexiptv 
I had the similar case, when you have the different SSH port, which is provided by your VPS provider.
In that case please try the following:
1. Open VNC terminal and perform the following command: `sudo ufw allow 22/tcp`
2. Then to access to VPS machine via SSH: `scp -P 22 root@ipaddress:/tmp/id_ssh_ed25519 .ssh/id_vpn_wgunix`
3. If no success, then please modify your `/etc/ssh/sshd_config` file and temporary allow password login:
```
PasswordAuthentication yes
```
After changes restart your sshd service: `sudo service sshd restart`
4) If you copied your key to your local machine, please revert your chenges in your sshd_config and restart the sshd service

Hope it helps

**Comment by apexiptv** [comment]
My port was always set as 22. when I looked at that /etc/ssh/sshd_config file there was an empty file after reaching that part on the video I showed above. Up until that point I was logged into shh. perfectly fine. It was like the file was glitched and cleared out during the bootstrap.

![image](https://user-images.githubusercontent.com/42727116/215932769-b80bfc1a-7a04-4526-8fcd-39f60fd4be0c.png)

Even after I reinstalled my OS and everything, it still is happening.. I generated keys through puttygen this time and copied the public key into the setup process.. It gives this error when I do scp -P 22 root@ipaddress:/tmp/id_ssh_ed25519 .ssh/id_vpn_wgunix

![image](https://user-images.githubusercontent.com/42727116/215934825-83f2f549-a1fd-4c81-a5a0-94e798c24803.png)

**Comment by apexiptv** [comment]
I scrolled up and saw this error as well... 

![image](https://user-images.githubusercontent.com/42727116/215955759-831bc31c-c0d0-42da-9ab3-e4d7da766888.png)

**Comment by apexiptv** [comment]
I'm wondering if I can run fast panel for normal hosting, seems like there would be a port conflict..

**Comment by apexiptv** [comment]
Got it passed that, now the site isn't redirecting to the wg.domain after verifying 2fa page.
just sits on this screen 
![image](https://user-images.githubusercontent.com/42727116/215993334-c068c116-bb96-442b-a95e-f63dd85cba98.png)

**Comment by apexiptv** [comment]
I connect via phone dataplan but not at my boarding school wifi it's being blocked.  Our tower for cell data is so far away. It's being blocked. 
Hotspotshield vpn is one of the few that work at my boarding school and I'm trying to do my own vpn that will be less noticed since most students here use hotspot shield. 

I'm wondering if switching ports/protocols would get around it.

**Comment by notthebee** [comment]
Hi @apexiptv , is the issue resovled? 
If so, feel free to close.
