### ISSUE TITLE
nothebe.ee is down or refusing requests

### ISSUE THREAD

**Issue by keystroke3** [notthebee/ansible-easy-vpn#133]
- [x] I've read the [FAQ](https://github.com/notthebee/ansible-easy-vpn/blob/main/FAQ.md) and my problem isn't described there.
- [x] I've also searched through the existing issues, and my problem hasn't been brought up

**Describe the issue**
I tried running the command
```bash
wget https://notthebe.ee/vpn -O bootstrap.sh && bash bootstrap.sh
```
but got 
```bash
--2023-02-10 05:12:55--  https://notthebe.ee/vpn
Resolving notthebe.ee (notthebe.ee)... 5.2.76.41
Connecting to notthebe.ee (notthebe.ee)|5.2.76.41|:443... failed: Connection refused.
```
Visiting https://notthebe.ee seems to be refusing connections or is down

**Environment:**
- VPS OS Ubuntu 22.04, Arch Linux
- VPS Provider Linode,Local Computer

**Comment by notthebee** [comment]
Fixed in 42b988888b6cc4d218d4ac5f3dae9e69b8dfec7f
