### ISSUE TITLE
How do i get wireguard to run through a different port

### ISSUE THREAD

**Issue by xeltea** [notthebee/ansible-easy-vpn#137]
The code works perfect, thank you however i would like to change the wireguard port as 51280 is blocked. Ive changed my endpoint to port 3478 on my wireguard mobile app but i dont know what to change in the files to get the connection to go through 3478 instead of 51280. Any suggestions would be great thank you.

**Comment by xeltea** [comment]
*51820 my bad, question still remains though

**Comment by notthebee** [comment]
Copy this line to custom.yml, replace the port and re-run `bootstrap.sh`:
https://github.com/notthebee/ansible-easy-vpn/blob/main/inventory.yml#L35

**Comment by xeltea** [comment]
ive confirmed that my VPS provider doesnt block the port but it still doesnt connect, i there anything else i should change?

**Comment by notthebee** [comment]
You also need to change the port in your client config

**Comment by xeltea** [comment]
oh of course, stupid me, my bad. All works now, thank you!
