### ISSUE TITLE
source .bashrc fails

### ISSUE THREAD

**Issue by eyenalxai** [notthebee/ansible-easy-vpn#14]
```
RUNNING HANDLER [authelia : source .bashrc] ********************************************************************************************************************************************
fatal: [localhost]: FAILED! => changed=true 
  cmd: source $HOME/.bashrc
  delta: '0:00:00.006717'
  end: '2022-07-24 08:29:14.556962'
  msg: non-zero return code
  rc: 127
  start: '2022-07-24 08:29:14.550245'
  stderr: '/bin/sh: 1: source: not found'
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

I believe it's from there: https://github.com/notthebee/ansible-easy-vpn/blob/main/roles/authelia/handlers/main.yml

Fails on Ubuntu 20.04 and 22.04 from Hetzner 🥲

I run the script first thing after I ssh'd into a server as root

**Comment by notthebee** [comment]
Looks like your default shell isn't bash. Try setting it to bash and run the playbook (not the bootstrap.sh script) again:
```
cd $HOME/ansible-easy-vpn
ansible-playbook run.yml
```

I will explicitely specify /bin/bash as the shell in a future commit.

**Comment by notthebee** [comment]
See if this helps https://github.com/notthebee/ansible-easy-vpn/commit/7210933931630c881daf2b0a5612165bd96ee3b6

**Comment by eyenalxai** [comment]
Works now! Thank you very much for creating this!
