### ISSUE TITLE
Error when running the palybook (again)

### ISSUE THREAD

**Issue by antonw-25** [notthebee/ansible-easy-vpn#152]
- [x] I've read the [FAQ](https://github.com/notthebee/ansible-easy-vpn/blob/main/FAQ.md) and my problem isn't described there.
- [ ] I've also searched through the existing issues, and my problem hasn't been brought up

**Describe the issue**
I ran the playbook on a different VPS and I keep getting this error

**Logs (if applicable)** 
Paste any relevant error messages here:
```
Waiting for verification...
Cleaning up challenges
An unexpected error occurred:
There were too many requests of a given type :: Service busy; retry later.
Please see the logfiles in /var/log/letsencrypt for more details.
```
Then I ran bash /var/log/letsencrypt/letsencrypt.log      (not sure if this does anything)
```
/var/log/letsencrypt/letsencrypt.log: line 1: 2023-03-01: command not found
/var/log/letsencrypt/letsencrypt.log: line 2: 2023-03-01: command not found
/var/log/letsencrypt/letsencrypt.log: line 3: syntax error near unexpected token `('
/var/log/letsencrypt/letsencrypt.log: line 3: `2023-03-01 23:48:50,629:DEBUG:certbot.main:Discovered plugins: PluginsRegistry(PluginEntryPoint#manual,PluginEntryPoint#null,PluginEntryPoint#standalone,PluginEntryPoint#webroot)'
```

**Environment:**
- Client OS: Mac OS
- VPS OS Ubuntu 20.04
- VPS Provider Digital Ocean

**Comment by notthebee** [comment]
Let's Encrypt had an outage yesterday, which affected the generation of the certificates. According to their status page, it's been fixed. Try re-running the playbook

**Comment by antonw-25** [comment]
Hi,
Sorry, I am still running into said issue. Thanks

**Comment by notthebee** [comment]
Hey. Yep, unfortunately, the Let's Encrypt staging servers still seem to be overloaded. I'm working to fix it on my end, but for now, you can remove `--staging` from these lines in bootstrap.sh (line 250 and line 252):
https://github.com/notthebee/ansible-easy-vpn/blob/9f98d536f713347543b604e73046e22f5109541a/bootstrap.sh#L250
https://github.com/notthebee/ansible-easy-vpn/blob/9f98d536f713347543b604e73046e22f5109541a/bootstrap.sh#L250

**Comment by antonw-25** [comment]
Thanks a lot. Yeah, I looked at their website and other people are having problems too. thanks a lot
