### ISSUE TITLE
bunkerity/bunkerweb:1.4.2 keeps restarting

### ISSUE THREAD

**Issue by hupratt** [notthebee/ansible-easy-vpn#158]
- [*] I've read the [FAQ](https://github.com/notthebee/ansible-easy-vpn/blob/main/FAQ.md) and my problem isn't described there.
- [*] I've also searched through the existing issues, and my problem hasn't been brought up

**Describe the issue**
Hi Wolfgang, thank you for all your video and content. I just started up an EC2 instance on AWS and i get the same error whether I run your playbook on a ubuntu 20.04 or 22.04. The installation runs fine but then the url doesnt work so I tried to debug the situation and it turns out that the container bunkerity/bunkerweb:1.4.2 keeps restarting. Did you ever encounter this weird situation?

Cheers man

**Logs (if applicable)** 
Paste any relevant error messages here:
```
![image](https://user-images.githubusercontent.com/38809698/224519081-03d985fb-86f2-44a0-acf2-c9f9ec86dd59.png)```

**Environment:**
- Client OS:  N/A
- VPS OS  ubuntu 20.04 or 22.04
- VPS Provider aws

**Comment by notthebee** [comment]
Looks like this case from the FAQ: https://github.com/notthebee/ansible-easy-vpn/blob/main/FAQ.md#q-i-get-a-secure-connection-failed-error-when-trying-to-access-the-wireguard-webui-in-the-browser

What does `docker logs bunkerweb` say?

**Comment by hupratt** [comment]
Awesome ! it works now. It turns out I used a domain name that was too long for nginx to process. I started from another fresh install and now it works smoothly. 

![2023-03-12_13-47](https://user-images.githubusercontent.com/38809698/224546715-15092c60-55a0-4890-9fe2-8217f9791e20.png)
