### ISSUE TITLE
No such filer or directory

### ISSUE THREAD

**Issue by simpsonnth** [notthebee/ansible-easy-vpn#159]
- [ ] I've read the [FAQ](https://github.com/notthebee/ansible-easy-vpn/blob/main/FAQ.md) and my problem isn't described there.
- [ ] I've also searched through the existing issues, and my problem hasn't been brought up

**Describe the issue**
After running the wget command the bash bootsrap.sh reports that the cd: /root/ansible-easy-vpn: no such file or directory. 
Running on DigitalOcean 6$ droplet

**Logs (if applicable)** 
Paste any relevant error messages here:
```
log cd: /root/ansible-easy-vpn: no such file or directory
```

**Environment:**
- Client OS: Windows
- VPS OS Ubuntu 22:04 LTS
- VPS Provider Digital Ocean

**Comment by notthebee** [comment]
Thanks for letting me know. Just reverted the latest commit, try again

**Comment by simpsonnth** [comment]
Works now thanks
