### ISSUE TITLE
Increasing IP Address Range and IP Table Routing

### ISSUE THREAD

**Issue by simpsonnth** [notthebee/ansible-easy-vpn#161]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Maybe within the boostrap.sh allowing the user to specify the range. There's no obvious way that I can see at the moment to edit the IP address range, or adding this into the FAQ showing the location to edit would be helpful. Also within the FAQ highlighting how to access the IP tables to route the traffic of a specific website to another IP address. This comes in handy when websites are being blocked due to being on VPN. 

**Additional context**

**Comment by notthebee** [comment]
Hey! I'm sorry, I'm not quite sure what exactly you're trying to achieve. Would you mind pointing me to some documentation?

**Comment by simpsonnth** [comment]
Hi, No worries here is the link to some documentation: https://www.procustodibus.com/blog/2021/01/wireguard-endpoints-and-ip-addresses/ - basically we want to change the address from 10.8.0.1/24 to 10.8.0.1/22. However, editing the following file /opt/docker/wg-easy/wg.conf does not hold the changes. 

The second part to my question is accessing the IP tables to route the traffic: https://www.wireguard.com/netns/  e.g. "ip route add 163.172.161.0/32 via 192.168.1.1 dev eth0"

**Comment by simpsonnth** [comment]
@notthebee do you think this is doable on your script or within the docker container?
