### ISSUE TITLE
Server refuse to connect

### ISSUE THREAD

**Issue by Doxestic** [notthebee/ansible-easy-vpn#162]
After rebooting the server the webpage opens up with no problem but when i try to login to server it refuses 
What is the problem cuz it never happened before

**Comment by Tchuch0** [comment]
in my case after reboot neither the page or the machine reply to a simple ping

**Comment by notthebee** [comment]
What OS are you using?

**Comment by Tchuch0** [comment]
Ubuntu 20. Was Perfect until the reboot

**Comment by schttrj** [comment]
Same issue here. Ubuntu 22.04 (latest).

![screenshot](https://user-images.githubusercontent.com/26226853/236609853-ad5bdad7-6faf-4bc3-b295-312e7ca714b2.jpeg)

I press "Enter" and it stops here. I can't see anything from the red mark area. Prompt: _The connection is refused or access denied or permission denied._

**Comment by yernende** [comment]
In my case fail2ban appeared to cause a similar problem, stopping it and starting again did the trick
```
sudo service fail2ban stop
sudo service fail2ban status
```

**Comment by Mhowser** [comment]
I noticed that the script changed my SSH port back to the default `22` in `/etc/ssh/sshd_config` and the UFW firewall rules. I think this should be detected by the script to prevent further confusion and connectivity problems for users who already have an established server.

**Comment by notthebee** [comment]
Should be fixed in v0.2

**Comment by Mhowser** [comment]
@notthebee the playbook is still resetting the ssh port back to 22.
![image](https://github.com/notthebee/ansible-easy-vpn/assets/24195572/654dc6d2-49ad-497f-aa2f-9ff426181291)

**Comment by notthebee** [comment]
@Mhowser my comment was referring to the original issue. The SSH port is controlled by this variable in the config: https://github.com/notthebee/ansible-easy-vpn/blob/main/inventory.yml#L58

**Comment by Mhowser** [comment]
Got it, thanks for pointing me in the right direction!
