### ISSUE TITLE
Warning: Identity file not accessible...

### ISSUE THREAD

**Issue by mrduszek** [notthebee/ansible-easy-vpn#163]
I needed a fresh installation of my Windows 11. Now I can't access my vps. I execute

ssh -p 22 [username]@[server ip] -i .ssh/id_vpn_[username]

and get "Warning: Identity file .ssh/id_vpn_[username] not accessible: No such file or directory.
[username]@[server ip]: Permission denied (publickey)."

Any ideas how login on my VPS?

**Comment by notthebee** [comment]
Congratulations, you've removed your private SSH key 😁
Your VPS provider should normally offer a way to log in to your server via a VNC console. From there you can log in with your username and password and set up a new SSH key pair

**Comment by mrduszek** [comment]
Thank you, I'm also proud of myself :/ How to setup a new SSH key pair and does I have to make changes to the whole script?

**Comment by notthebee** [comment]
https://www.digitalocean.com/community/tutorials/how-to-create-ssh-keys-with-putty-to-connect-to-a-vps
