### ISSUE TITLE
how do dns over tls,https

### ISSUE THREAD

**Issue by yremac** [notthebee/ansible-easy-vpn#166]
I want to use DoT it on my phone but I don't know how to use it bunkerweb ,and on PC DoH ,but I can only do it without a busy port or with ngx proxy .

**Comment by notthebee** [comment]
The project already sets up DNS-over-HTTPS if answer "Yes" to the respective question in the bootstrap script. No further actions required on the client side.

As for DoT – that's not something I'm familiar with

**Comment by yremac** [comment]
I meant in adguard home you can configure DNS encryption, I want to do DoH and DoT through it to get access to the DNS server with filtering without connecting to VPN
how to configure the web ui in bunkerweb via your ansible?

**Comment by notthebee** [comment]
You can't really use the DNS functionality separately from the VPN. That would require making your DNS service publicly accessible, and that's a very bad idea.

**Comment by yremac** [comment]
I understand the risks, how to configure the web ui in bunkerweb via your ansible?

**Comment by notthebee** [comment]
Sorry, but if you understand the risks, you should be skilful enough to figure it out yourself.

**Comment by yremac** [comment]
Okay, thanks for your work
