### ISSUE TITLE
Error when generating inventory

### ISSUE THREAD

**Issue by noteffex** [notthebee/ansible-easy-vpn#17]
This happens when I try to create a user.
Output:
```
Welcome to ansible-easy-vpn!

This script is interactive
If you prefer to fill in the inventory.yml file manually,
press [Ctrl+C] to quit this script

Enter your desired UNIX username
Username: vpn
sed: can't read /root/ansible-easy-vpn/inventory.yml: No such file or directory
root@personal:/home/ubuntu#
```

**Comment by notthebee** [comment]
```
cp -rv /home/ubuntu/ansible-easy-vpn /root/ansible-easy-vpn
cd /root/ansible-easy-vpn && bash bootstrap.sh
```

**Comment by D3SOX** [comment]
Maybe this should be noted under Usage in the README.
Something along the lines of:

## As root
```bash
Command1
```

# As non-root user
```bash
Command2
```

Or add a at the top in the bootstrap script check if it runs as root

**Comment by D3SOX** [comment]
Maybe this should be noted under Usage in the README.
Something along the lines of:

## As root
```bash
Command1
```

# As non-root user
```bash
Command2
```


Or make the command automatically elevate if the uid is not 0

Or add a at the top in the bootstrap script check if it runs as root

**Comment by notthebee** [comment]
I've made some changes since the issue was created – the script should now use the $HOME variable instead of the hardcoded path `/root/ansible-easy-vpn`.

That being said, I should also implement a root privilege check
