### ISSUE TITLE
Timezone hardcoded

### ISSUE THREAD

**Issue by higuita** [notthebee/ansible-easy-vpn#170]
**Describe the issue**
After running this ansible, authelia failed to accept my 2FA.
After some debug i found that my time was wrong and checking the ansible, i found that timezone is hardcoded in the inventory.yml to Europe/Berlin and not where overwritten to my local timezone. Also found that my phone also had the time a little out of sync. Fixed both, removed everything and redeployed and now everything works. In the end, not totally sure if the wrong timezone was also a problem or not, but i think it would be  better to add to the bootstrap a detection/question for the timezone anyway, as for sure, not everyone is located in Germany

Thanks for this ansible and for your youtube channel!

**Comment by higuita** [comment]
Only now notices that there is a PR related to this problem: https://github.com/notthebee/ansible-easy-vpn/pull/167 

Probably removing the timezone is a good alternative... but i think asking the users would be a better option.
A brand new server, it may be helpful to have the ansible set it up... on a existent server, it is probably already configured

**Comment by notthebee** [comment]
Solved by ff5f721
