### ISSUE TITLE
TASK [authelia : Make sure the Redis container is created and running

### ISSUE THREAD

**Issue by arsaces7** [notthebee/ansible-easy-vpn#174]
msg: 'Error starting container ddd98683c42d6803cad9588c457e3f694c9e43b864ded92f32104d334cbd6d0a: 400 Client Error for http+docker://localhost/v1.42/containers/ddd98683c42d6803cad9588c457e3f694c9e43b864ded92f32104d334cbd6d0a/start: Bad Request ("failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "proc" to rootfs at "/proc": mount proc:/proc (via /proc/self/fd/6), flags: 0xe: permission denied: unknown")'

**Comment by notthebee** [comment]
What distro are you using?

**Comment by arsaces7** [comment]
ubuntu 20

**Comment by notthebee** [comment]
Would you mind describing how you solved the issue?

**Comment by arsaces7** [comment]
> Would you mind describing how you solved the issue?

Vps wasn't kvm , i think that cause the problem but I'm not sure
