### ISSUE TITLE
Install error : docker_network : Create the wg network >> got an unexpected keyword argument ''chunked''

### ISSUE THREAD

**Issue by derChristoph** [notthebee/ansible-easy-vpn#179]
- [x] I've read the [FAQ](https://github.com/notthebee/ansible-easy-vpn/blob/main/FAQ.md) and my problem isn't described there.
- [x] I've also searched through the existing issues, and my problem hasn't been brought up

**Describe the issue**
I just follows the instructions an the problem occurs when after the Playbook started, i tried rebooting but still the same.

**Logs (if applicable)** 
Paste any relevant error messages here:
```
TASK [docker_network : Create the wg network] **************************************************************************
fatal: [localhost]: FAILED! => changed=false
  msg: 'Error connecting: Error while fetching server API version: request() got an unexpected keyword argument ''chunked'''
```
![image](https://user-images.githubusercontent.com/13977320/236250262-3cf2cdd0-a15c-4e81-aeef-1a3ad20bc7b1.png)

**Environment:**
- Client OS: Windows 11 Terminal
- VPS OS: Ubuntu 20.04
- VPS Provider: dedipath.com >> 512MB OpenVZ SSD VPS

**Comment by bendaek** [comment]
Same issue here

**Comment by arsaces7** [comment]
> * [x]  I've read the [FAQ](https://github.com/notthebee/ansible-easy-vpn/blob/main/FAQ.md) and my problem isn't described there.
> * [x]  I've also searched through the existing issues, and my problem hasn't been brought up
> 
> **Describe the issue** A clear and concise description of what the issue is.
> 
> **Logs (if applicable)** Paste any relevant error messages here:
> 
> ```
> TASK [docker_network : Create the wg network] **************************************************************************
> fatal: [localhost]: FAILED! => changed=false
>   msg: 'Error connecting: Error while fetching server API version: request() got an unexpected keyword argument ''chunked'''
> ```
> 
> ![image](https://user-images.githubusercontent.com/13977320/236250262-3cf2cdd0-a15c-4e81-aeef-1a3ad20bc7b1.png)
> 
> **Environment:**
> 
> * Client OS: Windows 11 Terminal
> * VPS OS: Ubuntu 20.04
> * VPS Provider: dedipath.com >> 512MB OpenVZ SSD VPS

same here
ubuntu 20.4 - hetzner

**Comment by derChristoph** [comment]
Maybe that can help, but I have no idea how to implement it in this nice Script: https://github.com/docker/docker-py/issues/3113

**Comment by axelblaze88** [comment]
Same here

**Comment by notthebee** [comment]
Looks like a bug in upstream. I'll take a look at it tonight

**Comment by Drknz056** [comment]
Hi WolfGang, love your work! I'm also receiving the same error. Is this an error on fetching the script side?

**Comment by bendaek** [comment]
That would be awesome. I tried the playbook a few weeks ago and it worked perfectly. I tinkered a bit then wanted to restart from scratch and got this error. I thought it was my system 😃
Thanks again.

**Comment by notthebee** [comment]
Last round of tests ran without errors, so the issue should be fixed now :)
Please do a `git pull` on your end and re-run `bash bootstrap.sh`

**Comment by derChristoph** [comment]
Works for me! Tank you!
