### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by derChristoph** [notthebee/ansible-easy-vpn#182]
- [x] I've read the [FAQ](https://github.com/notthebee/ansible-easy-vpn/blob/main/FAQ.md) and my problem isn't described there.
- [x] I've also searched through the existing issues, and my problem hasn't been brought up

**Describe the issue**
seems my VPS dose not support it, is there a way around it?

**Logs (if applicable)** 
Paste any relevant error messages here:
```
$ wg-quick down wg0
$ wg-quick up wg0
Error: WireGuard exited with the error: Cannot find device "wg0"
This usually means that your host's kernel does not support WireGuard!
    at /app/lib/WireGuard.js:65:19
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /app/lib/WireGuard.js:63:9
```

**Environment:**
- Client OS: Windows 11 Terminal
- VPS OS: Ubuntu 20.04
- VPS Provider: dedipath.com >> 512MB OpenVZ SSD VPS

**Comment by notthebee** [comment]
You can use wireguard-go https://github.com/WireGuard/wireguard-go

**Comment by derChristoph** [comment]
And how do i combine that with your nice script ?

**Comment by notthebee** [comment]
Just set up wireguard-go on your box, and then proceed with the script as usual.
I don't have any experience with wireguard-go, so you're on your own, unfortunately

**Comment by derChristoph** [comment]
I have "solfed" my problem by changeing the VPS to: https://vpshostingservice.co/store/server-host-linux-vps-ssd
With the Coupon & Promo Code LEB4OFF i got a reocuring discount of 4 USD, you have to chose monthly billing to get to the 1 US per month.

The Script worked like a charm! Not i have so manny othe questions @notthebee do you have a discord?

**Comment by janolehuebner** [comment]
Any other solutions for this? I have the same problem. 2FA works but then the wg. .. subdomain says 502
