### ISSUE TITLE
Install error : [ssh : Generate an SSH key pair] >> got an unexpected keyword argument  "Need bcrypt module"

### ISSUE THREAD

**Issue by aunixdude** [notthebee/ansible-easy-vpn#183]
- [x] I've read the [FAQ](https://github.com/notthebee/ansible-easy-vpn/blob/main/FAQ.md) and my problem isn't described there.
- [x] I've also searched through the existing issues, and my problem hasn't been brought up

**Describe the issue**
I just follows the instructions an the problem occurs when after the Playbook started, i tried rebooting but still the same.
```
cat  ansible-easy-vpn/custom.yml

username: "unixdude"
root_host: "vpn.example.com"
dns_nameservers: "cloudflare"
enable_ssh_keygen: true
```

**Logs (if applicable)** 
Pasted the  relevant error messages down:
```
TASK [ssh : Generate an SSH key pair] ****************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: cryptography.exceptions.UnsupportedAlgorithm: Need bcrypt module
fatal: [localhost]: FAILED! => changed=false
  msg: 'unexpected error occurred: Need bcrypt module'
```
![image](https://user-images.githubusercontent.com/102591344/236561035-775b49bd-8249-4b53-9113-eb45d76a7973.png)

**Environment:**
- Client OS: Linux
- VPS OS: Debian 11
- VPS Provider:  OpenStack Nova 26.1.0 >> z.large 4C/4Gb ram

**Comment by aunixdude** [comment]
**it worked after i reRun with my Keypair**
```
cat ansible-easy-vpn/custom.yml

username: "unixdude"
root_host: "vpn.example.com"
dns_nameservers: "cloudflare"
enable_ssh_keygen: false
ssh_public_key: "ssh-ed25519 xxxxxxxxxxxxxxxxxxxxxxxxxxxx/xxxxxxxxxx unix@localhost"
```

**Comment by notthebee** [comment]
Should work now after the last commit
