### ISSUE TITLE
error

### ISSUE THREAD

**Issue by sohrab2021** [notthebee/ansible-easy-vpn#185]
*
fatal: [localhost]: FAILED! => changed=false
  commands:
  - /usr/sbin/ufw status verbose
  - /usr/bin/grep -h '^### tuple' /lib/ufw/user.rules /lib/ufw/user6.rules /etc/ufw/user.rules /etc/ufw/user6.rules /var/lib/ufw/user.rules /var/lib/ufw/user6.rules
  - /usr/sbin/ufw logging on
  msg: |-
    ERROR: Could not update running firewall

**Comment by notthebee** [comment]
Please re-create the issue and make sure to fill out the provided template.
In order to diagnose the issue, I need to know which VPS provider and OS you're running this on
