### ISSUE TITLE
url not opening 

### ISSUE THREAD

**Issue by arsaces7** [notthebee/ansible-easy-vpn#189]
- [x] I've read the [FAQ](https://github.com/notthebee/ansible-easy-vpn/blob/main/FAQ.md) and my problem isn't described there.
- [x] I've also searched through the existing issues, and my problem hasn't been brought up

after latest update on your scrip i get this at the final step and the url not opening
(I tried it many times before and works fine on Hetzner)
![image](https://github.com/notthebee/ansible-easy-vpn/assets/55933676/14def6bc-d3f3-4fcf-9d40-0fa8953d067f)

and : bash bootstrap.sh
bash: bootstrap.sh: No such file or directory

**Environment:**
- Client OS: [Windows,]
- VPS OS [Ubuntu 20.04]
- VPS Provider [Hetzner]

**Comment by arsaces7** [comment]
> What does it look like in the browser? Are you getting any kind of an nginx error, or does the page time out?

time out
This site can’t be reached took too long to respond.

**Comment by notthebee** [comment]
I see.
Do you still have access to the server via SSH?
And if yes, does executing the following commands solve the issue?
```
sudo ufw allow 443
sudo ufw allow 80
sudo ufw allow 51820
```

If not, what does `sudo ufw status` say?

**Comment by arsaces7** [comment]
> [<img alt="@arsaces7" width="40" height="40" src="https://avatars.githubusercontent.com/u/55933676?s=80&amp;v=4">](/arsaces7)
> 
> Add heading textAdd bold text, <Ctrl+b>Add italic text, <Ctrl+i>
run the command bit still not opening 

To                         Action      From
--                         ------      ----
22/tcp                     ALLOW       Anywhere
10.8.2.5 8443/tcp          ALLOW       Anywhere
10.8.2.5 8080/tcp          ALLOW       Anywhere
10.8.2.8 51820/udp         ALLOW       Anywhere
22/tcp (v6)                ALLOW       Anywhere (v6)

**Comment by arsaces7** [comment]
I tried with duckdns multiole times with different distros but same result

**Comment by notthebee** [comment]
I've reverted the firewall commit. It should work for you now on a fresh system, or after doing the following:
```
sudo ufw reset && sudo ufw disable
```
