### ISSUE TITLE
having issue running the script

### ISSUE THREAD

**Issue by noaaf500** [notthebee/ansible-easy-vpn#193]
**Describe the issue*
first of all Thank you for this script! this is an awesome project, and much appreciated.  

I'm a noob in ubuntu but I've used this script on a VPS server and it worked perfectly!
so I subscribed to another VPS from  dedicontrol.com which is running ubuntu 20.04.
tried to run the script same as before but i keep getting the same Error shown

'' Encrypting the variables
New Vault password:
Confirm New Vault password:
Encryption successful

Success!
Would you like to run the playbook now? [y/N]: y
Vault password:

PLAY [Install and configure ansible-easy-vpn] ***********************************************************************

TASK [Gathering Facts] **********************************************************************************************
ok: [localhost]

TASK [Set the AWS and Letsencrypt staging facts] ********************************************************************
ok: [localhost]

TASK [system : Load OS-specific vars] *******************************************************************************
ok: [localhost]

TASK [system : Configure the system] ********************************************************************************
included: /root/ansible-easy-vpn/roles/system/tasks/essential.yml for localhost

TASK [system : Check if locale exists] ******************************************************************************
ok: [localhost]

TASK [system : Create locale] ***************************************************************************************
changed: [localhost]

TASK [system : Check if language exists] ****************************************************************************
ok: [localhost]

TASK [system : Create language] *************************************************************************************
changed: [localhost]

TASK [system : Get current locale and language configuration] *******************************************************
ok: [localhost]

TASK [system : Parse 'LANG' from current locale and language configuration] *****************************************
fatal: [localhost]: FAILED! =>
  msg: |-
    Unexpected templating type error occurred on ({{ locale_status.stdout | regex_search('LANG=([^
    ]+)', '\\1') | first }}): 'NoneType' object is not iterable

PLAY RECAP **********************************************************************************************************
localhost                  : ok=9    changed=2    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

root@linux:~# ''

**Environment:**
- Client OS: [Linux]
- VPS OS [Ubuntu 20.04]
- VPS Provider [dedicontrol.com]
[LOG.txt](https://github.com/notthebee/ansible-easy-vpn/files/11635382/LOG.txt)

**Comment by notthebee** [comment]
Fixed in v0.2
