### ISSUE TITLE
Authelia and Bunkerweb not starting

### ISSUE THREAD

**Issue by camopov** [notthebee/ansible-easy-vpn#2]
![Screenshot from 2022-07-23 15-17-50](https://user-images.githubusercontent.com/96944108/180606749-93eecfef-1f86-49fe-b25c-683c1cfef734.png)
this happens after running the playbook

**Comment by notthebee** [comment]
Look at Authelia and Bunkerweb logs for possible issues:

```
docker logs authelia
docker logs bunkerweb
```

**Comment by camopov** [comment]
forgot to make a dns entry for auth.example.com working now

**Comment by crabix** [comment]
> forgot to make a dns entry for auth.example.com working now

hi, i guess i run into the same error 
2022/08/13 13:26:33 [error] 81#81: *18 directory index of "/opt/bunkerweb/www/" is forbidden, client: 12.34.567.899, server: www.example.com, request: "GET / HTTP/1.1", host: "wg.XXXXX.duckdns.org"

could you explain what you mean with dns entry? on the vps? and pointing to where? or is it a different problem?

**Comment by camopov** [comment]
You need to make a dns entry for auth.XXXXXX.duckdns.com

**Comment by crabix** [comment]
ok but pointing auth.xxxx.duckdns.org to where?

**Comment by camopov** [comment]
> ok but pointing auth.xxxx.duckdns.org to where?

To the same IP where wg.xxxx.dickens.org points to
