### ISSUE TITLE
'-' in domain name characters

### ISSUE THREAD

**Issue by Ssri7774** [notthebee/ansible-easy-vpn#20]
Loving your work, just a suggestion that we can add '-' in here:
echo "Enter your domain name"
echo "The domain name should already resolve to the IP address of your server"
echo
read -p "Domain name: " root_host
**until [[ "$root_host" =~ ^[a-z0-9\.]*$ ]]; do**
  echo "Invalid domain name"
  read -p "Domain name: " root_host
done

Error I got:
Enter your domain name
The domain name should already resolve to the IP address of your server

Domain name: ab-cd-xyz.duckdns.org
**Invalid domain name**

DuckDNS accepts below characters:
error: invalid domain entered, valid characters are : A-Z, 0-9, **-**

**Comment by notthebee** [comment]
Closed by 2637c13
