### ISSUE TITLE
How do I forward a port from the public IP of the VPS to the private IP of my PC at home?

### ISSUE THREAD

**Issue by rm76** [notthebee/ansible-easy-vpn#207]
First of all, thank you for your amazing script, it's incredible how much stuff can be automated these days...
It would be awesome if this help request also became a feature request, but for now, I'd be satisfied to just know how I can forward network packets hitting a port on the public IP of the VPS to a port on the private IP of my PC at home.
I'm still pretty new to Github, so please forgive me if I was supposed to post somewhere else for help requests...

**Comment by notthebee** [comment]
As of now – you can't. Adding this function would blow up the scope of this playbook, but if you have an implementation in mind – feel free to submit a PR.

**Comment by rm76** [comment]
Thanks anyway. Right now I don't even know how to make it happen manually, let alone script it, but I'm going to try!
I'm guessing the containerization makes it even harder, but that's okay, I'm in for a good challenge!

**Comment by derChristoph** [comment]
@rm76 Dow did it go? i wannt exact the same thing

**Comment by rm76** [comment]
> 

Sorry, other things had higher priority so, no advancement so far.
