### ISSUE TITLE
No Auto-Updates

### ISSUE THREAD

**Issue by Baylandiego** [notthebee/ansible-easy-vpn#209]
I'm getting no auto-updates to the OS, i checked when the last time something was updated/upgraded using:
grep "install " /var/log/dpkg.log
grep "upgrade " /var/log/dpkg.log 
and i didn't get anything the docker is also not updated i read about the docker containers updated by you but i'm not sure about the OS

- Client OS: macOS
- VPS OS Ubuntu 22.04.2 
- VPS Provider Vpshostingservice

**Comment by notthebee** [comment]
Is there a file called  '/var/log/unattended-upgrades.log'? If yes, you might be able to find the logs there.
The docker container versions are not updated automatically (yet)

**Comment by Baylandiego** [comment]
yeah i found these logs, thanks
