### ISSUE TITLE
bootstrap.sh: line 104: dig: command not found

### ISSUE THREAD

**Issue by Ssri7774** [notthebee/ansible-easy-vpn#21]
Need to install dig using the below command:

apt-get install dnsutils

**Comment by notthebee** [comment]
Normally, this should already install it https://github.com/notthebee/ansible-easy-vpn/blob/9e2bb97ed6473969e5c66419e64c6f4efdc8c655/bootstrap.sh#L43

What VPS are you running?

**Comment by D3SOX** [comment]
Follow-up from #10 

https://github.com/notthebee/ansible-easy-vpn/blob/0ab6a2944f835b6d3ef4bc81e6c34d5077882dbe/bootstrap.sh#L43

Shouldn't it always install dnsutils, regardless of the architecture?

**Comment by notthebee** [comment]
You're right 🤦
Fixed by c254b98a63f172b49cabf20dffe0f425dc1c890e

**Comment by Ssri7774** [comment]
> 

I'm just following all the steps in your video. Using RackNerd itself.
