### ISSUE TITLE
VPN stopped suddenly working 

### ISSUE THREAD

**Issue by techdevmaestro** [notthebee/ansible-easy-vpn#210]
the vpn stopped suddenly working since yesterday i can't access the wg or adguard website but i can ping the website i tried to reboot a couple of times the vpn but it didn't helped 

the only thing that i'm getting after rebooting is this: 

![Screen Shot 2023-07-25 at 10 29 56 PM](https://github.com/notthebee/ansible-easy-vpn/assets/66648373/793e6ff2-d671-4e7c-86d4-8e89799f696e)

- Client OS: macOS
- VPS OS: Ubuntu 22.04
- VPS Provider Vpshostingservice

**Comment by notthebee** [comment]
Do you have access to the command line?
Execute the following commands and paste the results here

```
docker ps
```
```
docker logs -f authelia
```
```
docker logs -f wireguard
```

**Comment by Baylandiego** [comment]
https://we.tl/t-Q2y5CeUrXh

i can't upload the output anywhere because it's too big so i just made a rtf file and uploaded it to wetransfer

**Comment by Baylandiego** [comment]
https://we.tl/t-SGk1OkhmYb

i can't upload the output anywhere because it's too big so i just made a txt file and uploaded it to wetransfer

**Comment by Baylandiego** [comment]
do you have any idea how to fix it?
