### ISSUE TITLE
VPN Connects, but no internet

### ISSUE THREAD

**Issue by Druganov1** [notthebee/ansible-easy-vpn#211]
- [x] I've read the [FAQ](https://github.com/notthebee/ansible-easy-vpn/blob/main/FAQ.md) and my problem isn't described there.
- [x] I've also searched through the existing issues, and my problem hasn't been brought up

**Describe the issue**
As the title says, i connect to the VPN with the wireguard app, it establishes connection but there is no internet.

At first i thought it was a government block since i am in Iran currently and they almost block all commercial VPN's. So i changed the wireguard port to 443 in custom.yml as the FAQ explained. But after that still the same.
Then i contacted my co-worker that is in the Netherlands. He also ran into the same issue, VPN succesfully connects but no internet connection, nothing will load.

I dont know how to grab any logs.

**Extra info**
I have my own domainname and in the DNS settings i set an A record to my VPS IP. So i will try to do a fresh install on another VPS with duckDNS see if that works.

**Environment:**
- Client OS: [IOS]
- VPS OS [Ubuntu 20.04]
- VPS Provider [[DutchIS](https://dutchis.net/)]

**Comment by Druganov1** [comment]
Currently i also tried it on AWS on an free tier ec2 instance, everything installed and tried duckDNS.

Installation worked perfectly but yet again, it handshakes with the server but no acces to internet.

**Comment by MuhammadJamee** [comment]
same for me!! client connects however no internet...

**Comment by Druganov1** [comment]
> same for me!! client connects however no internet...

Hey! 

So i found out that the complete protocol is blacklisted and they detect it easily, i recommend you to take a look at [X-UI](https://seakfind.github.io/2021/10/10/X-UI/) you can set up V2Ray clients here pretty easily and if you use the correct client settings, and xtls etc it would be completely undetected. Make sure you have a good VPS running in a country that does not have any restrictions, it will work fine.

Speed wise? Its amazing, there is almost no diffrence whatsoever when you connect to the server, and you can have an unlimited amount of clients, label them etc, its just everything you need.

This is currently as we speak still working in Iran.
