### ISSUE TITLE
Default webUI/2fa ports

### ISSUE THREAD

**Issue by exciterx** [notthebee/ansible-easy-vpn#213]
Hello! 

Can you please provide information how we can change not only WG port but also default WebUI/2fa ports (80/443) to free up them for other use. 

It would be nice to make it configurable in custom.yml

**Comment by notthebee** [comment]
Unfortunately that's not possible – port 80 is necessary to generate the TLS certificates. Changing the port 443 should be easy though – take a look at the bunkerweb role and the Bunkerweb documentation

**Comment by radwanHb** [comment]
hi , it can be a very good idea , because servers can run apache or nginx to serves websites
