### ISSUE TITLE
keep getting Error 500 internal server error after reboot WEBUI

### ISSUE THREAD

**Issue by papmanou** [notthebee/ansible-easy-vpn#220]
- [ x ] I've read the [FAQ](https://github.com/notthebee/ansible-easy-vpn/blob/main/FAQ.md) and my problem isn't described there.
- [ x] I've also searched through the existing issues, and my problem hasn't been brought up

**Describe the issue**
After finalising the setup following the very clear playbook, I'm unable to get the wireguard webUI due to an Internal Server Error code 500 when trying to reach http(s)://wg-yobaleko.com

**Environment:**
- Client OS: [Mac OS]
- VPS OS [e.g. Ubuntu 20.04]
- VPS Provider [DesiVPS]

**Comment by papmanou** [comment]
Solved , issue related to SMTP authentication not working properly for MFA notifications. Disabling the email feature solved the 500 internal server error.

**Comment by KidA001** [comment]
> Solved , issue related to SMTP authentication not working properly for MFA notifications. Disabling the email feature solved the 500 internal server error.

how do you disable the email feature..
