### ISSUE TITLE
WireGuard-UI - installation

### ISSUE THREAD

**Issue by papmanou** [notthebee/ansible-easy-vpn#222]
Hello,

I'm getting more and more request from family and friends to use my WireGuard vpn server, but I'm loosing visibility due to the lack of functionality on the default web UI. Is there a way to install "WireGuard-UI" on top of this without breaking the existing setup ?

Thanks agin for the nice peace of work.

**Comment by notthebee** [comment]
Not with this playbook. You can take a look at the wg-easy repo to install it separately and transfer all your configs from the native Wireguard installation: https://github.com/wg-easy/wg-easy
