### ISSUE TITLE
feature: Rosenpass support

### ISSUE THREAD

**Issue by donBarbos** [notthebee/ansible-easy-vpn#224]
Thanks to [Rosenpass](https://rosenpass.eu) in 2023 it became possible to use the post-quantum authenticated key exchange algorithm.
I suggest using Rosenpass for peer key exchange, at least optional.
I haven't yet seen any popular Wireguard manager/installer use Rosenpass to configure.
[Guide](https://rosenpass.eu/#start) | [Source Code](https://github.com/rosenpass/rosenpass)

**Comment by notthebee** [comment]
The Wireguard part is taken care of wg-easy. Outside of forking it, I have no influence over the cipher used by Wireguard. Please submit the feature request there: https://github.com/wg-easy/wg-easy
