### ISSUE TITLE
Debian 12 support

### ISSUE THREAD

**Issue by staticdev** [notthebee/ansible-easy-vpn#228]
**Is your feature request related to a problem? Please describe.**
Self-explanatory.

**Comment by staticdev** [comment]
I didn't even try since on the readme of initial page said it supports one of the selected supported distros and there is only Debian 11. Maybe it is only missing from the list there.

**Comment by 3a-33** [comment]
Ah okay, I'll put it on my list to get around to, if it works I'll update the issue and submit a PR to update :)

**Comment by notthebee** [comment]
Fixed in https://github.com/notthebee/ansible-easy-vpn/commit/146c32c763e0ba5843908c2a4c68f45d167d61e4

**Comment by staticdev** [comment]
Thanks a lot @notthebee !
