### ISSUE TITLE
UFW not installed / enable after install

### ISSUE THREAD

**Issue by rhbkweb** [notthebee/ansible-easy-vpn#229]
- [x] I've read the [FAQ](https://github.com/notthebee/ansible-easy-vpn/blob/main/FAQ.md) and my problem isn't described there.
- [x] I've also searched through the existing issues, and my problem hasn't been brought up

**Describe the issue**
After installation, when check "ufw status"  not found if not previously installed or it shows "Status: inactive" if previous installled on the VPS before running the VPN script installation. Both ways, UFA does is not enable.

**Environment:**
- VPS OS: Ubuntu 22.04
- VPS Provider: Racknerd

**Comment by notthebee** [comment]
UFW has been replaced with iptables in the latest release. The README has now been corrected to reflect that https://github.com/notthebee/ansible-easy-vpn/commit/46a9fc73ef49d9495a047de550be4cb18134dc2e
