### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by Chinaboy5216** [notthebee/ansible-easy-vpn#23]
After 2 days trying to get this running now again i get errors thrown out. EDIT: running as root by the way

This time it seems like a scripting error or so i believe it to be:

TASK [system : Create a login user] ************************************************************************************************************************************************
fatal: [localhost]: FAILED! => 
  msg: 'Unexpected templating type error occurred on ({{ user_password | password_hash(''sha512'') }}): secret must be unicode or bytes, not int'

**Comment by notthebee** [comment]
Does your user password consist of only numbers, by any chance?

**Comment by Chinaboy5216** [comment]
> Does your user password consist of only numbers, by any chance?

yes it does, is that an issue? It's not mentioned in the video so I expected it not to be an issue. Ok i check again, currently reinstalling the vps. Thanks Wolfgang

**Comment by notthebee** [comment]
It's not an issue per se, I just didn't test it with that. I'll fix it in a minute

**Comment by Chinaboy5216** [comment]
ok i'll wait then before testing again. thanks mate

**Comment by notthebee** [comment]
Fixed by #24
