### ISSUE TITLE
Logout Button does not show

### ISSUE THREAD

**Issue by rhbkweb** [notthebee/ansible-easy-vpn#230]
- [x] I've read the [FAQ](https://github.com/notthebee/ansible-easy-vpn/blob/main/FAQ.md) and my problem isn't described there.
- [x] I've also searched through the existing issues, and my problem hasn't been brought up

**Describe the issue**
After login (admin intrface)the top right button Logout does not show. There is no way to logout.

**Environment:**
- VPS OS: Ubuntu 22.04
- VPS Provider: Tested on Racknerd and GreenCloudVPS

**Comment by notthebee** [comment]
I'm not sure which admin interface you mean exactly (Authelia, AdGuard or wg-easy). Unfortunately I have no control over the respective user interfaces, please submit the issues to the upstream projects
