### ISSUE TITLE
Request to update README.md or the script

### ISSUE THREAD

**Issue by hakatu** [notthebee/ansible-easy-vpn#233]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when running this script on an LXC and forgot that a newly created LXC does not have the `iptable` and `nginx` installed

**Describe the solution you'd like**
Suggest adding pre-installation to README.md or update the bash to include these two packages

**Additional context**
No

**Comment by notthebee** [comment]
This script is supposed to be ran on a VPS or a virtual machine – LXCs and other containzerized hosts are not supported. I'll make sure to add this to the README.
