### ISSUE TITLE
scrip error on aws instance

### ISSUE THREAD

**Issue by vorajeeah** [notthebee/ansible-easy-vpn#234]
- [x] I've read the [FAQ](https://github.com/notthebee/ansible-easy-vpn/blob/main/FAQ.md) and my problem isn't described there.
- [x] I've also searched through the existing issues, and my problem hasn't been brought up

**Describe the issue**
I am trying to run the script on an aws instance using putty. I am logging in as ubuntu with the putty key. when I run the scrip I get the following errors

**Logs (if applicable)** 
Domain: vorajee.duckdns.org
  Type:   connection
  Detail: 50.18.139.253: Fetching http://vorajee.duckdns.org/.well-known/acme-challenge/trYwOQMoOJ3JkXLcIO79DmH7c5CFzPter2pLPvcaBfE: Timeout during connect (likely firewall problem)

  Domain: wg.vorajee.duckdns.org
  Type:   connection
  Detail: 50.18.139.253: Fetching http://wg.vorajee.duckdns.org/.well-known/acme-challenge/2Y0NR5OxBouk4hEU-yBCUGon2v4IEg3_aBhJkViMT1s: Timeout during connect (likely firewall problem)

Hint: The Certificate Authority failed to download the challenge files from the temporary standalone webserver started by Certbot on port 80. Ensure that the listed domains point to this machine and that it can accept inbound connections from the internet.

Some challenges have failed.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.
ubuntu@ip-172-31-13-58:~$ Domain name: vorajee.duckdns.org

Running certbot in dry-run mode to test the validity of the domain...
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Account registered.
Requesting a certificate for vorajee.duckdns.org and 2 more domains

Certbot failed to authenticate some domains (authenticator: standalone). The Certificate Authority reported these problems:
  Domain: auth.vorajee.duckdns.org
  Type:   connection
  Detail: 50.18.139.253: Fetching http://auth.vorajee.duckdns.org/.well-known/acme-challenge/raY8PiMYP-IT5nSyW3z9a1STW00ZtU6DGkdsEvyGBBI: Timeout during connect (likely firewall problem)

  Domain: vorajee.duckdns.org
  Type:   connection
  Detail: 50.18.139.253: Fetching http://vorajee.duckdns.org/.well-known/acme-challenge/1_37guDHqEMHtoWDZgC-Hi7sjMULcYUAXGg3QBuOp1E: Timeout during connect (likely firewall problem)

  Domain: wg.vorajee.duckdns.org
  Type:   connection
  Detail: 50.18.139.253: Fetching http://wg.vorajee.duckdns.org/.well-known/acme-challenge/PasNb_tRE1cfbv4BUTokMFKYZEkA0wL2q5Zi8awKsNU: Timeout during connect (likely firewall problem)

```

**Environment:**
- Client OS:  Linux
- VPS OS  Ubuntu 22.04
- VPS Provider AWS free tier with elastic ip adress

**Comment by xploz1on** [comment]
Hi there.
I have tried this in an AWS EC2 Free tier too. I had no problems at all (I used duckdns too).
Make sure that you have the proper PORTS OPEN withing AWS Firewall rules. 
This looks to be the problems.

**Comment by vorajeeah** [comment]
HI

Thanks for the reply.

Please help me by explaining the ports that need to be opened within AWS
Firewall rules.
The first vps I set up was a few days ago on aws, so I am very
inexperienced.

Thanks

**Comment by xploz1on** [comment]
> HI Thanks for the reply. Please help me by explaining the ports that need to be opened within AWS Firewall rules. The first vps I set up was a few days ago on aws, so I am very inexperienced. Thanks

Sure thing. You need to Open:
80 / TCP
443 / TCP
51820 / UDP

Open those and the script should work without problems. Best of luck!

**Comment by vorajeeah** [comment]
Thank you so much for your kindness.
I really appreciate it.
I will try when I get an aws instance up again.
I received a notification saying that my 1 GB of transfer allocated on the
free tier was almost finished.
It should be 100GB. Trying to sort it out with customer care at the moment
