### ISSUE TITLE
DNS leaktest only shows selected upstream servers (and not internal/unbound)

### ISSUE THREAD

**Issue by GoodBreeches** [notthebee/ansible-easy-vpn#249]
Thanks Wolfgang for this amazing software!

I enabled AdGuard Home during installation.

Not sure if this is an issue or not but my leak tests show :

1) On my phone:  just my upstream DNS servers (Quad9), and

2)  On my home PC: the upstream DNS (Quad9) plus my home IP (which I assume is due to my router DNS (which uses to my local Pihole unbound as DNS server).

Is this correct? Shouldn't I see the AdGuard upstream server 127.0.0.1 or my VPS IP address (if it's working as a DNS server) as well as Quad9?

I have not configured my phone to point to a private DNS server. If I should, what address to I point it to (seems to be asking for a domain name and not an IP address)?

Note. If I Test upstreams in AdGuard GUI (under DNS settings) it returns "Specified DNS servers are working correctly" (everything is default as per installation configuration)

**Comment by notthebee** [comment]
That sounds OK to me. Adguard only forwards your queries to an upstream DNS, and doesn't resolve the addresses itself, as far as I know. 

I'll close this for now, but if anyone knows more on the subject – feel free to chime in.
