### ISSUE TITLE
AdGuard Logging is enabled by default

### ISSUE THREAD

**Issue by KidA001** [notthebee/ansible-easy-vpn#252]
**Is your feature request related to a problem? Please describe.**
TLDR AdGuard logging is enabled by default on the install. It also has client IP logging enabled (i'm unclear if this is tracking the VPN user's IP or just the local machine).

**Describe the solution you'd like**
I'm not sure if these settings can be set on install, but I feel like the default should have logging disabled and Anonymize Client IP enabled as well. If this is not possible, then maybe a logging message telling users that they should disable this.

**Comment by KidA001** [comment]
Actually - The settings are right in here. Glad to make a PR but maybe there's a reason logging is enabled
https://github.com/notthebee/ansible-easy-vpn/blob/main/roles/dns/files/AdGuardHome.yaml

**Comment by notthebee** [comment]
Fixed in https://github.com/notthebee/ansible-easy-vpn/commit/146c32c763e0ba5843908c2a4c68f45d167d61e4
