### ISSUE TITLE
Erro no auth.  site com erro 500 Internal Server Error

### ISSUE THREAD

**Issue by rcinformatica1** [notthebee/ansible-easy-vpn#253]
O meu, finaliza tudo corretamente, só que dá erro ao abrir o site, 
erro no servidor, o que posso fazer para solucionar o problema,

no domínio principal,  https://nomedosite.com , https://auth.nomedosite.com,  https://wg.nomedosite.com , aparece assim 

Bad Gateway 502
The request was not completed. The server received an invalid response from the upstream server.

o que pode ser isso, alguém pode me ajudar a resolver o problema por favor....

ao finalizar consigo logar normal no servidor, utilizando o parâmetro normal, 

ssh -p 22 usuário@númerodoseuip -i ~/.ssh/path-to-your-key 

como eu faço para solucionar esse erro ao abrir a página
https://wg.nomedosite.com

**Comment by rcinformatica1** [comment]
![serv](https://github.com/notthebee/ansible-easy-vpn/assets/117770606/4e66f8b9-5ea0-4dbb-b385-8ecf643e4be0)

O meu, finaliza tudo corretamente, só que dá erro ao abrir o site, 
erro no servidor, o que posso fazer para solucionar o problema,

no domínio principal,  https://nomedosite.com , https://auth.nomedosite.com,  https://wg.nomedosite.com , aparece assim 

Bad Gateway 502
The request was not completed. The server received an invalid response from the upstream server.

o que pode ser isso, alguém pode me ajudar a resolver o problema por favor....

ao finalizar consigo logar normal no servidor, utilizando o parâmetro normal, 

ssh -p 22 usuário@númerodoseuip -i ~/.ssh/path-to-your-key 

como eu faço para solucionar esse erro ao abrir a página
https://wg.nomedosite.com

**Comment by notthebee** [comment]
Please re-create an issue in English.
