### ISSUE TITLE
Question - Open port to Wireguard client

### ISSUE THREAD

**Issue by kkl1974** [notthebee/ansible-easy-vpn#254]
Hi

Apologies for opening an issue - not a bug just struggling with my own configuration 

My easy VPN runs on an OVH VPS in the cloud (Debian 11)

I want to expose port 41150 on a server at home to the web 

I've tried 

sudo iptables -A INPUT -p tcp -s 10.8.0.9 --dport 41190 -j ACCEPT
and sudo iptables-save

but i still can't ping the port externally

please forgive my ignorance, any help or info to point me in the right direction appreciated 

thanks

**Comment by notthebee** [comment]
You can use the `iptables_allow_rules` variable to create additional firewall rules. The syntax can is shown here: https://github.com/notthebee/ansible-easy-vpn/blob/main/inventory.yml#L90
