### ISSUE TITLE
Script fails at restoring iptables firewall rules

### ISSUE THREAD

**Issue by krishnapramodaradhi** [notthebee/ansible-easy-vpn#255]
- [x] I've read the [FAQ](https://github.com/notthebee/ansible-easy-vpn/blob/main/FAQ.md) and my problem isn't described there.
- [x] I've also searched through the existing issues, and my problem hasn't been brought up

**Describe the issue**
While running the firewall script, the script errors out with the below error.
```
****fatal: [localhost]: FAILED! => changed=false
  msg: |-
    Unable to start service iptables: Job for iptables.service failed because the control process exited with error code.
    See "systemctl status iptables.service" and "journalctl -xe" for details.
```
I tried searching the whole file system but unable to find iptables-restore anywhere. Any help will be appreciated.

**Logs (if applicable)** 
Paste any relevant error messages here:
```
● iptables.service - Restore iptables firewall rules
     Loaded: loaded (/etc/systemd/system/iptables.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Tue 2023-11-21 10:34:59 GMT; 6min ago
    Process: 36320 ExecStart=/sbin/iptables-restore -n /etc/iptables.conf (code=exited, status=203/EXEC)
   Main PID: 36320 (code=exited, status=203/EXEC)

Nov 21 10:34:59 racknerd-73dfaf systemd[1]: Starting Restore iptables firewall rules...
Nov 21 10:34:59 racknerd-73dfaf systemd[36320]: iptables.service: Failed to execute command: No such file or directory
Nov 21 10:34:59 racknerd-73dfaf systemd[36320]: iptables.service: Failed at step EXEC spawning /sbin/iptables-restore: No such file or directory
Nov 21 10:34:59 racknerd-73dfaf systemd[1]: iptables.service: Main process exited, code=exited, status=203/EXEC
Nov 21 10:34:59 racknerd-73dfaf systemd[1]: iptables.service: Failed with result 'exit-code'.
Nov 21 10:34:59 racknerd-73dfaf systemd[1]: Failed to start Restore iptables firewall rules.
```

**Environment:**
- Client OS: Windows
- VPS OS : Ubuntu 20.04 64-bit
- VPS Provider: RackNerd

**Comment by alestef** [comment]
Hello, the solution outlined in this comment https://github.com/notthebee/ansible-easy-vpn/issues/221#issuecomment-1745657624 seemed to fix it for me

**Comment by alisa4y** [comment]
Hi 

For me the problem was it try to reading it from the /sbin path,

I fixed it with this:
`sudo ln -s /usr/sbin/iptables-restore /sbin/iptables-restore`

Make sure the iptables-restore path is right("/usr/sbin/iptables-restore"). you can find out with this command: 
`which iptables-restore`

If it was different replace the "/usr/sbin/iptables-restore" with it.

**Comment by krishnapramodaradhi** [comment]
Thanks @alisa4y. This fixed the issue
