### ISSUE TITLE
Include AdGuard Admin URL in Instructions

### ISSUE THREAD

**Issue by sunrays2993** [notthebee/ansible-easy-vpn#256]
I selected to install AddGuard at the beginning of the setup script, but then didn't know how to manage it.

I assumed it was the subdomain of 'https://adguard.MYDOMAIN.org', as was correct.

I would good if this was on the list of 6 instructions for future installs; when the script has completed. Maybe number 7.
Also it is not on the main GitHub page or the FAQ

I think there is only the subdimains of
* wg
* adguard

Is that correct?

Thanks.

**Comment by 0x09AF** [comment]
there is also
- auth

**Comment by notthebee** [comment]
The script explicitly tells you which subdomains need to point to the VPS: https://github.com/notthebee/ansible-easy-vpn/blob/main/bootstrap.sh#L242
