### ISSUE TITLE
Add AlmaLinux compat

### ISSUE THREAD

**Issue by 0xlord** [notthebee/ansible-easy-vpn#257]
**Is your feature request related to a problem? Please describe.**
I am using Alma Linux and would love to use this script. I've seen that it used to have RockyLinux support and I was wondering why it was kicked out. My hope is that this ticket raises awareness, that there are RHEL users out there using Alma (and Rocky I pressume) Linux which would love to benefit from this script.

**Describe the solution you'd like**
Include dnf syntax into the script so it can run on Alma/Rocky (again), please.

**Additional context**
I'd love to provide help and a testing environment.

**Comment by notthebee** [comment]
Sorry, but for now, I can only reasonably provide support for Debian-based distros. Including support for RPM-based distros would blow up the scope too much to where I wouldn't have time or resource to reasonably develop and test the playbook
