### ISSUE TITLE
Cloudflare zero trust tunnel

### ISSUE THREAD

**Issue by JasonB73** [notthebee/ansible-easy-vpn#264]
- [ ] I've read the [FAQ](https://github.com/notthebee/an(https://github.com/notthebee/ansible-easy-vpn/blob/main/FAQ.mdsible-easy-vpn/blob/main/FAQ.md) and my problem isn't described there.
- [ ] I've also searched through the existing issues, and my problem hasn't been brought up

FAQ 404 error on URL looking for issues. 
https://github.com/notthebee/ansible-easy-vpn/blob/main/FAQ.mdsible-easy-vpn/blob/main/FAQ.md

**Describe the issue**
A clear and concise description of what the issue is.

Using Cloudflare zero trust tunnel to my ubuntu 22.04 server.
tunnel setup with Debian installer and showing connected.

  During the installation script it asked for domain.
I add the domain that is set for my tunnel.
Won't let me pass because it shows my main ISP not the IP of my Server.

  Is there any way to get past this?
I don't want to open router / firewall rules.
Thanks

**Logs (if applicable)** 
Paste any relevant error messages here:
```
log
```

**Environment:**
- Client OS: [Linux]
- VPS OS [Ubuntu 22.04]
- VPS Provider [On site esxi 7 Host Dell R640]

**Comment by notthebee** [comment]
Sorry, this is not a supported configuration at the moment. If you wish, you can fork the repository and adjust the code according to your use case.

**Comment by JasonB73** [comment]
Thanks for getting back to me on it.
