### ISSUE TITLE
Question how to investigate sites that do not open / resolve

### ISSUE THREAD

**Issue by Japhys** [notthebee/ansible-easy-vpn#269]
Not really an issue, more a question. First of all this is really cool, I got this working with pretty basic knowledge of vps / vpn and docker. Pretty much all sites work. I do get a captcha for Google, probably because Racknerd gave me an ip with was previously abused. Anyway, I noticed ALL sites of DPG media are giving http2 errors. Disabling Adguard doesn't help, makes aense. Like I said pretty much all other sites work so I find this quite interesting. Is there a way to find out what causes this? 

All the sites mentioned here do not work

https://nl.m.wikipedia.org/wiki/DPG_Media

![Screenshot_20240107-122559](https://github.com/notthebee/ansible-easy-vpn/assets/24695937/7771232a-c564-4d73-a858-f87f5211a0bc)

**Comment by notthebee** [comment]
What happens if you `curl` the websites directly on the VPS?

**Comment by Japhys** [comment]
In the above case I get

`curl https://www.trouw.nl
curl: (92) HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)
`

**Comment by Japhys** [comment]
Exact same setup, different datacenter, new ip. No problems whatsoever anymore. Big plus: latency and speed is so much better. This is good enough to be permanently switched on. Thanks so much @notthebee. I enjoy your work/YouTube. Learning a lot
