### ISSUE TITLE
Local ip no domain

### ISSUE THREAD

**Issue by tavoweb** [notthebee/ansible-easy-vpn#276]
Are its possible tu run that script on vps that in local mashine to create vpn without domein name just opening publick ip some ports exept 80 443 to local mashine ... if so then how to skip domain part in setup...

**Comment by xploz1on** [comment]
You would be better of just installing [easy-wg](https://github.com/wg-easy/wg-easy) I use it via docker-compose
This way you just open the assigned Wireguard port to your local machine. Hope that helps!

**Comment by notthebee** [comment]
Not possible (or planned) with this playbook
