### ISSUE TITLE
E: Could not get lock /var/lib/dpkg/lock-frontend.

### ISSUE THREAD

**Issue by bokie1** [notthebee/ansible-easy-vpn#278]
wget https://notthebe.ee/vpn -O bootstrap.sh && bash bootstrap.sh
--2024-02-05 17:25:48--  https://notthebe.ee/vpn
Resolving notthebe.ee (notthebe.ee)... 104.21.84.248, 172.67.199.110, 2606:4700:3033::6815:54f8, ...
Connecting to notthebe.ee (notthebe.ee)|104.21.84.248|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://raw.githubusercontent.com/notthebee/ansible-easy-vpn/main/bootstrap.sh [following]
--2024-02-05 17:25:48--  https://raw.githubusercontent.com/notthebee/ansible-easy-vpn/main/bootstrap.sh
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 13115 (13K) [text/plain]
Saving to: ‘bootstrap.sh’

bootstrap.sh                  100%[=================================================>]  12.81K  --.-KB/s    in 0s

2024-02-05 17:25:48 (66.6 MB/s) - ‘bootstrap.sh’ saved [13115/13115]

Hit:1 http://us.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://us.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://us.archive.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
151 packages can be upgraded. Run 'apt list --upgradable' to see them.
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 1986 (unattended-upgr)
N: Be aware that removing the lock file is not a solution and may break your system.
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?

- [x] I've read the [FAQ](https://github.com/notthebee/ansible-easy-vpn/blob/main/FAQ.md) and my problem isn't described there.
- [x] I've also searched through the existing issues, and my problem hasn't been brought up

**Describe the issue**
A clear and concise description of what the issue is.

**Logs (if applicable)** 
Paste any relevant error messages here:
```
log
```

**Environment:**
- Client OS: [e.g. Windows, Linux]
- VPS OS [e.g. Ubuntu 22.04, Debian 11, Ubuntu 20.04]
- VPS Provider [e.g. Linode, Digital Ocean, Hetzner]

**Comment by notthebee** [comment]
As per the log messages, `unattended-upgrades` was already running on the server at the time you launched the script. Try again at a later time.
