### ISSUE TITLE
task ssh failed

### ISSUE THREAD

**Issue by l0rus** [notthebee/ansible-easy-vpn#28]
TASK [ssh : Update SSH configuration to be more secure] **************************************************************************************************
ok: [localhost] => (item={'regexp': '^PasswordAuthentication', 'line': 'PasswordAuthentication no'})
ok: [localhost] => (item={'regexp': '^PermitRootLogin', 'line': 'PermitRootLogin no'})
failed: [localhost] (item={'regexp': '^Port', 'line': 'Port 22'}) => changed=false
  ansible_loop_var: item
  item:
    line: Port 22
    regexp: ^Port
  msg: |-
    failed to validate: rc:255 error:/root/.ansible/tmp/ansible-tmp-1658779648.3071914-342945-79180311113602/tmpzfbob8dh line 135: Directive 'Port' is not allowed within a Match block
ok: [localhost] => (item={'regexp': '^PermitEmptyPasswords', 'line': 'PermitEmptyPasswords no'})
ok: [localhost] => (item={'regexp': '^X11Forwarding', 'line': 'X11Forwarding no'})
PLAY RECAP ***********************************************************************************************************************************************
localhost                  : ok=50   changed=8    unreachable=0    failed=1    skipped=14   rescued=0    ignored=0

**Comment by notthebee** [comment]
What VPS are you running this on?

**Comment by l0rus** [comment]
Ubuntu 20.04.4 LTS (GNU/Linux 5.4.0-42-generic x86_64)

**Comment by notthebee** [comment]
Have you changed anything in your sshd_config prior to running the script?
Can you post the contents of your `/etc/ssh/sshd_config`? (minus any sensitive information)

**Comment by l0rus** [comment]
Nope, havent touched anything.
[https://pastebin.com/ParVS0BT](sshd_config)
