### ISSUE TITLE
Possible issue with NATed IP from server during Let's Encrypt run

### ISSUE THREAD

**Issue by vinimp7** [notthebee/ansible-easy-vpn#281]
Hello! Since this is diverging a bit from the initial ticket I commented, I thought it would be better to open a new one.

I was having the same issue in the script when putting my duckdns information (It got stuck for several minutes), but now I'm pretty sure it's related to IPv6. I'm not using a VPS, instead I'm running it in a local server I'm bulding. 
My server was forcing IPv6 over IPv4 and the script couldn't catch the IP using:

`curl -s ipinfo.io/ip`

For debugging, I changed this command locally to:

`curl -4 ifconfig.co`

And it passed! But then, I noticed another issue. The cert-bot is not reaching my server due timeout:

`Fetching http://auth.******.duckdns.org/.well-known/acme-challenge/: Timeout during connect (likely firewall problem)"`

I'm not running anything on port 80 and my UWF is inactive, but I suspect my outbound IP is being NATed by my Internet Service Provider... And I'm not sure if this is an issue that can be workaroud :(

Is it possible to use IPv6 other than IPv4? If its better I can open a new bug/ticket.

_Originally posted by @vinimp7 in https://github.com/notthebee/ansible-easy-vpn/issues/90#issuecomment-1966613173_

**Comment by notthebee** [comment]
It's currently not possible to use IPv6 for the Wireguard server. If your server is not accessible from the Internet via IPv4, this playbook will not work for you, I'm afraid
