### ISSUE TITLE
Domain-based Exceptions for VPN Application

### ISSUE THREAD

**Issue by SourceSurfer** [notthebee/ansible-easy-vpn#284]
I am proposing a feature to enhance our VPN application by allowing users to specify domains or domain zones, such as ".ru", that the VPN should bypass. This functionality aims to improve user experience by providing flexibility in internet access without compromising overall security.

Problem Statement
Users often need to access certain sites directly, without VPN protection, due to reasons like accessing local content or avoiding VPN blocks. Currently, doing so requires manually disabling the VPN, which is inconvenient and poses a risk to privacy for other simultaneous browsing activities.

Proposed Solution
Introduce a feature allowing users to list domains that the VPN will automatically bypass. This ensures direct access for specified sites while maintaining VPN protection for all other internet traffic
Because now you have to turn it on/off up to 20 times a day VPN

**Comment by notthebee** [comment]
Please submit a feature request upstream: https://github.com/wg-easy/wg-easy
