### ISSUE TITLE
root ssh login

### ISSUE THREAD

**Issue by wp-coin** [notthebee/ansible-easy-vpn#287]
ought up

**Describe the issue**
after setup I can still login with root ssh user, shouldn't this be disabled?

**Environment:**
- Client OS: [e.g. Linux]
- VPS OS [e.g. Debian 12]
- VPS Provider [e.g. Linode]

**Comment by notthebee** [comment]
Have you rebooted your server after finishing the installation?

**Comment by MacchiaGuardala** [comment]
same, after rebooted

**Comment by notthebee** [comment]
I was not able to reproduce this on a Hetzner instance. The playbook includes a task that explicitly disables root login: https://github.com/notthebee/ansible-easy-vpn/blob/main/roles/ssh/tasks/main.yml#L61

So either the VPS provider is overriding the SSH configuration, or the playbook failed before configuring the SSH daemon.
