### ISSUE TITLE
add two containerized services, one exposed on the web and one reachable only by vpn

### ISSUE THREAD

**Issue by MacchiaGuardala** [notthebee/ansible-easy-vpn#289]
I don't know if this is the right channel to ask this question.

i just set up a vps coon debian12 with this, it works great as well as being simple and fast, thanks!

I'd like to add two containerized services, one exposed on the web and one reachable only by vpn, but I'm not sure where to start... can you give me any suggestions on this?

**Comment by MacchiaGuardala** [comment]
#129 and #196 look interesting, I forked the repository and will look at another time

**Comment by notthebee** [comment]
Unfortunately, I don't have the resources at the moment to implement the documentation/guide for this functionality. Feel free to fork the repository and modify the playbook to your needs
