### ISSUE TITLE
AWS EC2 instance.

### ISSUE THREAD

**Issue by AkioET** [notthebee/ansible-easy-vpn#29]
I have a Vultr VPS  that I'm trying to use for this, but when it's time to setup the SSH keys it reads:

>  Looks like you're running this script on an AWS EC2 instance.
> Please use the SSH keys defined in the Management Console to log in to the server after running the playbook.

After running the playbook:

> Almost done! Make sure to test your SSH connection in a new terminal window:
> ssh -p 22 akio@78.141.208.100 -i ~/.ssh/path-to-your-key

If I direct it to a key that I generated it fails and tries to connect with the password. I really have no idea what is happening...

**Comment by notthebee** [comment]
Looks like the AWS EC2 detection still needs some more work. I've reverted the relevant commits.

Please re-provision your server and launch the `bootstrap.sh` script again

**Comment by AkioET** [comment]
The original issue seems  to be working now, but I am now having problems with the login page, after setting everything up, when I enter the URL on my browser it returns with Error 500, should I open a new issue for this?

**Comment by notthebee** [comment]
Post the authelia and bunkerweb logs:
```
docker logs bunkerweb
docker logs authelia
```

**Comment by AkioET** [comment]
Hi, sorry, I actually managed to make this work and forgot to comment here, I'm now struggling to connect to the vpn on KDE since there seems to be no way to do this automatically and without using the wg-quick command...

**Comment by notthebee** [comment]
As far as I know, you can add a connection using `nmcli` regardless of the DE:
https://blogs.gnome.org/thaller/2019/03/15/wireguard-in-networkmanager/
