### ISSUE TITLE
Issue when running on machine with CaddyV2 installed

### ISSUE THREAD

**Issue by ruiisaactan** [notthebee/ansible-easy-vpn#290]
- [*] I've read the [FAQ](https://github.com/notthebee/ansible-easy-vpn/blob/main/FAQ.md) and my problem isn't described there.
- [*] I've also searched through the existing issues, and my problem hasn't been brought up

after entering my domain name into the script, it will try to validate my domain but gives an error about port 80 being in use by other processes. which on my system is caddyv2, i use this as a reverse proxy for my domains to have automatic lets encrypt singing for my plex and other local services. Is there any way around this or would i have to uninstall my services or separately run the vpn on another machine.

I was thinking that it could be possible to skip the domain name & lets-encrypt stage on the ansible-easy-vpn script and allow us to manually add the 3 required sub-domains on our own. feel free to correct me as this is just a thought.

other notes (i also have a static ip and my own domain name, i use namecheap for the domain and cloudflare to manage the domain, router also already has ports 80 and 443 forwarded to my server and static ip is properly setup on local network)

![image](https://github.com/notthebee/ansible-easy-vpn/assets/96219387/37ca6c76-47c9-42e0-b2e0-4ac5c0506558)

- Client OS: NA (Using VNC)
- OS KDE Neon 6 (Ubuntu 22.04)
- VPS Provider NA (Home Server)

**Comment by notthebee** [comment]
Sorry, this project needs the ports 80 and 443 to be open. If you're looking for a Wireguard server set up which doesn't requrie HTTP(s), https://github.com/Nyr/wireguard-install might be a better choice
