### ISSUE TITLE
the 2fa part doesn't work

### ISSUE THREAD

**Issue by anasp84** [notthebee/ansible-easy-vpn#291]
what am i supposed to do in the 2fa part, it doesn't work like in the video anymore i tried navigating manually to the page but it doesn't work

**Comment by maduro0077** [comment]
To get around the MFA registration, after you login to the website, click to register the device and it will ask for a code.  To get the code, goto your server and enter this command to get the code....  show_2fa
After you issue the command, it will say it has sent you an email but the actual email body and code will be printed in terminal after you issue the show_2fa command.  Then you can get to the captcha to add clients to wireguard.

**Comment by notthebee** [comment]
Authelia changed their 2FA interface since the video was made. @maduro0077 's instructions should work.
