### ISSUE TITLE
Create new clients from terminal

### ISSUE THREAD

**Issue by ahxan07** [notthebee/ansible-easy-vpn#293]
I have setup wireguard on EC2 instance. And it is working fine if I create the client from the WebUI. But I want to create the client from terminal. I have created the client and able to connect wireguard using this client. But "Data Sent" is in Bytes.
Can someone guide me on this.

**Comment by notthebee** [comment]
Sorry, this functionality is currently not planned. If you want a Wireguard server that can be fully managed from the CLI, https://github.com/Nyr/wireguard-install would be a better option
