### ISSUE TITLE
Pärast WireGuardiga ühendamist ei saa saitidele ligi (WireGuardi port on standardne).

### ISSUE THREAD

**Issue by DiMMMMM0N** [notthebee/ansible-easy-vpn#302]
Tere,

Mul on probleem, et WireGuardi kaudu ühendamisel ei saa ma ühelegi veebisaidile ligi. See probleem on kestnud juba rohkem kui nädal. Olen loonud uue WireGuardi serveri ja see töötab. Ma ei tea, kuidas probleemi lahendada. Palun aidake ja olen valmis jagama vajalikke logisid.
```

**Environment:**
- Client OS: Termux (Android)
- VPS OS: Debian 11
- VPS Provider: Hetzner

**Comment by DiMMMMM0N** [comment]
Uus server koos erineva skriptiga töötab.

**Comment by notthebee** [comment]
Please re-create the issue in English
