### ISSUE TITLE
The domain vpn.xxx.xxx.xxx does not resolve to the public IP

### ISSUE THREAD

**Issue by MrSchmaltz** [notthebee/ansible-easy-vpn#32]
Domain name: vpn.xxx.xxx

The domain vpn.xxx,.xxx does not resolve to the public IP of this server (firewall ip)

**Comment by notthebee** [comment]
As of now, the script doesn't support subdomains. You need to specify a TLD – the Wireguard WebUI will be available on wg.TLD, and the Authelia will be available on auth.TLD
