### ISSUE TITLE
Custom DNS Servers in wg-easy

### ISSUE THREAD

**Issue by idris3396** [notthebee/ansible-easy-vpn#33]
How to use custom DNS servers with wg-easy? 

I tried to add the WG_DEFAULT_DNS variable in the WireGuard task file but that change wasn't reflected when I ran the playbook.

I am new to Ansible. Is there a way to set custom DNS servers using the inventory.yml file?

I plan to use AdGuard DNS instead of the default 1.1.1.1.

Thanks!

**Comment by notthebee** [comment]
This should work: https://github.com/WeeJeWel/wg-easy/wiki/Using-WireGuard-Easy-with-Pi-Hole
If not, please submit an issue to the wg-easy repository

**Comment by notthebee** [comment]
Could you try creating a new client in the WebUI and looking at the config? Your custom DNS should be in there.

**Comment by D3SOX** [comment]
I wasn't aware that it's in the config, not on the server side. Working fine now!

**Comment by D3SOX** [comment]
Btw creating a new client was not necessary, just importing the config again works too
