### ISSUE TITLE
error when running playbook

### ISSUE THREAD

**Issue by andifischer** [notthebee/ansible-easy-vpn#34]
the bootstrap script runs all fine. when the playbook is starting i get the following error

_### ERROR! couldn't resolve module/action 'docker_network'. This often indicates a misspelling,        missing collection, or incorrect module path.

The error appears to be in '/home/anfisc/ansible-easy-vpn/roles/docker/tasks/main.yml': line        80, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Create the wg network
  ^ here_

Same issue when using root and with sudo user. 
i use  Linux Ubuntu 20.04 X86 64 Minimal Latest V2

do i need another version of ubuntu ?

**Comment by notthebee** [comment]
Looks like a recent version of Ansible broke some stuff. Do this:
`ansible-galaxy collection install community.docker`
