### ISSUE TITLE
The wireguard webpage doesn't work with Brave/Librewolf

### ISSUE THREAD

**Issue by GaRocK** [notthebee/ansible-easy-vpn#35]
I don't know if this is considered as an issue but I had to report, so others won't be confused if this happens. 

I tried to run the webpage after the playbook. 
The auth part runs fine (on brave had to disable shields). 
But after that, it was only possible to proceed to wireguard page with firefox. 

**It looks like a bug (infinite loop) on the redirect from the auth part to the wireguard webpage.**

More details: It didn't auto-redirected me to the wg webpage and kept me on the auth page so I had to do it manually. 
Even when the flag to redirect was on the browser it just didn't happen and I had to do it manually, and still doesn't work, keeps refreshing.

https://user-images.githubusercontent.com/4015712/181791698-ab92138c-9c54-4635-b41e-f86b0cc9fbb8.mp4

Now I recorded my screen and I'll be sharing with you guys what happens for more details.

This problem could be observed in **brave-bin(aur)/librewolf(aur)** on **arch.** 
I haven't tested if this occurs in other systems but I think it could be happening on them too.

So I recomend **not using these browsers** when setting up the things for this vpn, and using **firefox** instead.
Hope this helps someone.

Edit: after re-testing librewolf is now normalized and working fine. Brave is still not working.

**Comment by D3SOX** [comment]
I have no problems accessing the page in Brave (even with shields enabled) or LibreWolf. Are there any errors in the console?

**Comment by GaRocK** [comment]
After a while I could access the page via LibreWolf, don't know what changed. 

After trying it on brave now, no console errors appear.

**Comment by notthebee** [comment]
This is a known issue on the side of Authelia. With certain browsers you’ll need to navigate to wg.yourhost.com manually after authenticating.

**Comment by GaRocK** [comment]
> This is a known issue on the side of Authelia. With certain browsers you’ll need to navigate to wg.yourhost.com manually after authenticating.

yes but as you see in video, even doing that leads me to the infinite page refresh loop.

**Comment by egarim** [comment]
I have the same problem I get stuck on this page https://github.com/notthebee/ansible-easy-vpn/issues/232

**Comment by akadawa** [comment]
> This is a known issue on the side of Authelia. With certain browsers you’ll need to navigate to wg.yourhost.com manually after authenticating.

I have the same problem. navigate to wg.yourhost.com manually dont works.

tryed in vivaldi, edge, firefox
