### ISSUE TITLE
https not arrivable 

### ISSUE THREAD

**Issue by averagegnomedeenjoyer** [notthebee/ansible-easy-vpn#36]
The installation went well. But i cannot connect to website to download my VPN config

**Comment by notthebee** [comment]
Please follow the troubleshooting steps in the FAQ

**Comment by averagegnomedeenjoyer** [comment]
Ok, thank you

**Comment by averagegnomedeenjoyer** [comment]
I reinstalled everything, and after i changed my DNS it worked
