### ISSUE TITLE
Can't access the internet after successful connection

### ISSUE THREAD

**Issue by 0x0645** [notthebee/ansible-easy-vpn#37]
I finished the setup process and my VPN instance is up, but I can't use the internet after the connection is active.
I am using AWS EC2
what I see on my PC browser 
![PC view](https://user-images.githubusercontent.com/30774866/181812268-41294367-16f3-4bff-a7a7-3e7afb7220f6.png)
the connection on my phone
![Screenshot_2022-07-29-19-25-03-00](https://user-images.githubusercontent.com/30774866/181812301-10cdbfda-3288-48ee-aec3-5951a06f90c6.jpg)

**Comment by notthebee** [comment]
Take a look at the connection statistics. Does it only show "Data sent" or "Data received"?

**Comment by 0x0645** [comment]
Okay, something weird happened I always receive 0 KiB but I just found that to start receiving any data I need to spam open and close the connect button multiple times to establish a healthy connection. I think it is related to my county (Egypt) ISP I will do more research on this issue.

**Comment by 0x0645** [comment]
Update: WireGuard is blocked in Egypt the methodology of how it is being blocked is beyond my understanding but it seems it's [something related to the DPI system Egypt is using ](https://www.ntkernel.com/how-to-bypass-egypts-wireguard-ban/). I did figure out a way to use the setup using [Cloak ](https://github.com/cbeuw/Cloak) but I didn't like it, now I am using [tailscale ](https://tailscale.com/kb/1103/exit-nodes/)and it's working fine despite their setup using WireGuard.

**Comment by notthebee** [comment]
I will consider including Cloak in the future
