### ISSUE TITLE
Debian Support

### ISSUE THREAD

**Issue by GirishMahabir** [notthebee/ansible-easy-vpn#40]
Hello, 

I use Debian on most of my servers and this playbook runs quite well without many modifications.
So I decided to add Debian's support to it.

I will try to fork and work on it,

Kind Regards,
Girish Mahabir

**Comment by peterge1998** [comment]
bump

**Comment by peterge1998** [comment]
This is not completed???

**Comment by notthebee** [comment]
> This is not completed???

The PR has been stale since almost 2 months. If you want to submit your own, you're more than welcome
