### ISSUE TITLE
Port forwarding

### ISSUE THREAD

**Issue by EmperorPenguin18** [notthebee/ansible-easy-vpn#42]
I have a web service running on a local machine. With my previous VPN provider I had it setup so that the nginx would translate external VPN provided ports to the local port. This allowed me to access this service from anywhere while my server was using the VPN. I have now switched to using this script (really awesome so far thanks for making this and the video tutorial) and would like to continue doing things in a similar way. I tried to set it up in a way I thought would work, but nginx doesn't like the bunkerweb docker container that is using ports 80 and 443 (not sure why). I have no need to override these ports, I just want my port forwarding to co-exist with them. I am not very familiar with docker, and haven't used bunkerweb before so I'm not sure of the fix myself.

**Comment by notthebee** [comment]
Yep, your local nginx instance and bunkerweb wouldn’t be able to work together, since they both use the same ports. 

If you want to use this project with your own reverse proxy instead of Bunkerweb, you should fork the repository and adjust the playbook accordingly.
