### ISSUE TITLE
enable port forwarding

### ISSUE THREAD

**Issue by privacy313** [notthebee/ansible-easy-vpn#46]
i'm curious how to enable port forwarding with this set up in order to be fully connectable.
i tried following the instructions [here](https://www.procustodibus.com/blog/2021/04/wireguard-point-to-site-port-forwarding/#configure-wireguard-on-endpoint-a) without any luck. perhaps something to do with the containerization involved in this playbook. i don't have any experience with docker, so i might have overlooked something very fundamental.

**Comment by notthebee** [comment]
What exactly do you mean by port forwarding?

**Comment by privacy313** [comment]
i'm having similar issues as mentioned [here](https://forum.transmissionbt.com/viewtopic.php?t=18039).

**Comment by notthebee** [comment]
Unfrotunately, this is out of scope of this project. Feel free to fork the playbook and add the necessary UFW/iptables rules in your fork

**Comment by privacy313** [comment]
for anyone else experiencing this issue, i'll link the resources i used to get this working.
i found it easier to install wireguard on the vps myself from scratch rather than use this playbook -- since as @notthebee mentioned this usecase is outside the scope of this playbook.
perhaps it would be a simple alteration if you know docker/ansible well, but in my case it was quicker to pull everything up from scratch.

the [arch wiki](https://wiki.archlinux.org/title/WireGuard#Specific_use-case:_VPN_server) is helpful to set up the wireguard vpn.
i used the suggestions in [this post](https://serverfault.com/questions/1068004/firewalld-forwarding-functionality-with-wireguard) to get the firewall set up correctly (fwiw, firewalld just seems a bit cleaner than ufw & iptables, but either way should work).
i also needed to adjust the mtu settings outlined on [this page](https://keremerkan.net/posts/wireguard-mtu-fixes/) to get good speeds on my end.
