### ISSUE TITLE
Error install

### ISSUE THREAD

**Issue by sithortodox** [notthebee/ansible-easy-vpn#49]
`TASK [authelia : Add a 2FA alias to .bashrc] ***************************************************************************
fatal: [localhost]: FAILED! => changed=false
  msg: Path /home/root/.bashrc does not exist !
  rc: 257

RUNNING HANDLER [fail2ban : Restart fail2ban] **************************************************************************

RUNNING HANDLER [restart authelia] *************************************************************************************

PLAY RECAP *************************************************************************************************************
localhost                  : ok=41   changed=24   unreachable=0    failed=1    skipped=1    rescued=0    ignored=0

root@openvpnrusge:~#`
Shows this error and stops.  Please tell me the reason for this error.
VPS KVM Ubuntu 20.04

**Comment by notthebee** [comment]
P.S. From this error it seems that the username that you specified in the script is "root".
That is incorrect

**Comment by sithortodox** [comment]
I changed my login, but the error persisted

Сб, 6 авг. 2022 г. в 19:40, Wolfgang ***@***.***>:

**Comment by notthebee** [comment]
Have you git pulled the changes that I've made in 8c0e7df

**Comment by sithortodox** [comment]
I take the link that is indicated on github and paste it on the server.

I'm not very good at it. Please tell me what I need to do.

Сб, 6 авг. 2022 г. в 20:15, Wolfgang ***@***.***>:

**Comment by notthebee** [comment]
Do this:
```
cd $HOME/ansible-easy-vpn
git pull
ansible-playbook run.yml
```
