### ISSUE TITLE
playbook not running

### ISSUE THREAD

**Issue by W1zardK1ng** [notthebee/ansible-easy-vpn#50]
Would you like to run the playbook now? [y/N]: y
Vault password:
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  did not find expected key

The error appears to be in '/root/ansible-easy-vpn/secret.yml': line 1, column 29, but may
be elsewhere in the file depending on the exact syntax problem.

**Comment by Kliveman** [comment]
same thing here - got it aftert the "Would you like to run the playbook now? [y/N]:" prompt
```
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  . unacceptable character #x001b: control characters are not allowed
  in "<unicode string>", position 17
```

was running it all under windows 10 command prompt (turns out Windows Powershell does not recognize "&&" operator)

**Comment by W1zardK1ng** [comment]
Look like this issue is only with command prompt and Powershell.
script is working fine using putty software.
