### ISSUE TITLE
add gui to existing wg instance

### ISSUE THREAD

**Issue by SozinovD** [notthebee/ansible-easy-vpn#51]
I already have wireguard server installed on debian 10

I tried to use this script and it failed (i disabled os check)

Here is error messages i got:

.
- downloading role 'roles', owned by
 [WARNING]: - roles was NOT installed successfully: Content has no field named 'owner'

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

**Comment by notthebee** [comment]
Post the output of `ansible-galaxy --version`

**Comment by notthebee** [comment]
This is too old. You need at least 2.9 to run this playbook

Normally, installing Ansible via pip3 should give you the latest version:
```
ansible-galaxy [core 2.13.2]
```

Could be a Debian-specific issue. 
Right now I unforunately don't have the resources to support other distros apart from Ubuntu.
