### ISSUE TITLE
~/.ssh/id_vpn_disabled: No such file or directory

### ISSUE THREAD

**Issue by 3ighty2O** [notthebee/ansible-easy-vpn#53]
I'm using windows 11, vps is ubuntu 20.4.1. Keep running to the same problem and stuck at https://youtu.be/SMF301vQqJo?t=451.

**Comment by notthebee** [comment]
Follow the FAQ here: https://github.com/notthebee/ansible-easy-vpn#q-i-cant-copy-the-ssh-key-to-my-windows-machine

**Comment by 3ighty2O** [comment]
```
mkdir C:\Users\<username>\.ssh
scp -P 22 root@<server-ip-address>:/tmp/id_ssh_ed25519 C:\Users\<username>\.ssh
ssh -p 22 <username>@<server-ip-address> -i C:\Users\<username>\.ssh\id_ssh_ed25519
```
Sorry for the noob question, username here is my pc name or the UNIX username?

**Comment by notthebee** [comment]
This is a known issue, tracked in #52
