### ISSUE TITLE
Error while run playbook

### ISSUE THREAD

**Issue by l0rus** [notthebee/ansible-easy-vpn#57]
root@somevps~/ansible-easy-vpn# ansible-playbook run.yml
Vault password:
ERROR! couldn't resolve module/action 'openssh_keypair'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/root/ansible-easy-vpn/roles/ssh/tasks/main.yml': line 23, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  block:
    - name: Generate an SSH key pair
      ^ here

tired https://github.com/notthebee/ansible-easy-vpn/issues/34 and https://github.com/weareinteractive/ansible-ufw/issues/26 with no results

**Comment by notthebee** [comment]
Fixed. For now, do `ansible-galaxy collection install community.crypto`

**Comment by l0rus** [comment]
@notthebee now another issue
ERROR! couldn't resolve module/action 'authorized_key'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/root/ansible-easy-vpn/roles/ssh/tasks/main.yml': line 37, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Install the existing public key
  ^ here

**Comment by notthebee** [comment]
Okay, added `ansible.posix` to the requirements, this should fix it

**Comment by notthebee** [comment]
@l0rus is this resolved?

**Comment by l0rus** [comment]
@notthebee ye, this is fixed.
