### ISSUE TITLE
email config

### ISSUE THREAD

**Issue by arsaces7** [notthebee/ansible-easy-vpn#59]
I entered wrong SMTP credentials , and I don't know how to fix this.
now I'm getting error 500 as you said , can you guide me

**Comment by notthebee** [comment]
Have you followed the steps outlined in the FAQ?

**Comment by arsaces7** [comment]
do you mean run command : docker logs authelia
?
didn't find anything else

**Comment by notthebee** [comment]
This: https://github.com/notthebee/ansible-easy-vpn#q-ive-run-the-playbook-succesfully-but-now-i-want-to-change-the-domain-nameusernamepassword-how-can-i-do-that

**Comment by arsaces7** [comment]
can you tell me how to remove everything and do it again? i want to choose "no" in the setup process

**Comment by arsaces7** [comment]
i'll try it right now , thanks

**Comment by arsaces7** [comment]
there is a way to remove everything ? i want to set it up again

**Comment by notthebee** [comment]
Yes. Re-provision the VPS and start from scratch.

**Comment by arsaces7** [comment]
or remove the email config? sorry for asking so many questions

**Comment by notthebee** [comment]
Follow the steps in the FAQ under `Q: I've run the playbook succesfully, but now I want to change the domain name/username/password. How can I do that?`, and if the steps are unclear, re-provision the VPS.
