### ISSUE TITLE
Connect to to aws ec2 but no internet connection

### ISSUE THREAD

**Issue by yusyel** [notthebee/ansible-easy-vpn#61]
I tried aws free tire. Everything works like in the video but no internet connection when I try connect. I tried with windows and iphone. Let me know if you need additional log.

**Comment by notthebee** [comment]
Have you opened the wireguard port in the security group?

**Comment by yusyel** [comment]
@notthebee hmmm, for inbound 80,443 and 22 opened. for outbound it's all port. Do I need addition port for wireguard?

**Comment by in2gee** [comment]
...make sure that your Security Group allows inbound connections on 51820/udp, 80/tcp and 443/tcp.

**Comment by yusyel** [comment]
@in2gee  Thanks. Now working.
