### ISSUE TITLE
Issue with certbot when using aws ec2's 

### ISSUE THREAD

**Issue by TomYoungs** [notthebee/ansible-easy-vpn#63]
Hey love this project

I tried setting this up using a AWS ec2 but when I get to the stage of verifying the domain it shows the error: 
![image](https://user-images.githubusercontent.com/60447023/191058158-344b70b3-6ebe-4ca0-b98a-cf7c5c5fe2b4.png)

I'm guessing it's a setting AWS tweaked that's stopping this from working, any ideas?

**Comment by notthebee** [comment]
Are the ports 80, 443 and 51820 open in your Security Group?

**Comment by TomYoungs** [comment]
Ah great, that did it :) it literally mentioned that in the next step after checking the domain 🤦

Thanks for the help!
