### ISSUE TITLE
check your script apache2 

### ISSUE THREAD

**Issue by jfima** [notthebee/ansible-easy-vpn#65]
Running certbot in dry-run mode to test the validity of the domain...
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
Cleaning up challenges
Problem binding to port 80: Could not bind to IPv4 or IPv6.

apache is running on port 80 by default

**Comment by medanthelinium** [comment]
That's correct. You'll need to stop apache before issuing the certificate

**Comment by notthebee** [comment]
Make sure to stop apache before running the script

**Comment by jfima** [comment]
You have a very cool idea but poor execution.

I installed a clean ubuntu 20.4 on vps and tried to run your script. at the moment without intervention and hacking does not work.

The last step with the prohibition of password entry was especially frustrating.

the idea to make such a script is brilliant!

**Comment by notthebee** [comment]
What do you mean with "prohibition of password entry"?
