### ISSUE TITLE
Adguard and Unbound support

### ISSUE THREAD

**Issue by MagicJF** [notthebee/ansible-easy-vpn#66]
Hi, not really an issue but a question.

I am struggilng to complement this vps with adguard & unbound.

Are there plans to implement this features or I should try harder?

thxs!

**Comment by notthebee** [comment]
I'm currently struggling with that as well  😁 The feature is planned as in in the works

**Comment by notthebee** [comment]
To everyone who's interested: The experimental support for Adguard, Unbound and DoH has been merged in https://github.com/notthebee/ansible-easy-vpn/commit/97da7694b56b09172aca9c8b9f0732f0ecaa5cad

I've tested the playbook and it works both with and without Adguard on my Hetzner instance.

Please test the feature and let me know what you think!
