### ISSUE TITLE
Adding multiple SSH keys

### ISSUE THREAD

**Issue by trashdad** [notthebee/ansible-easy-vpn#70]
Attempted to add another ed25519 public key from another laptop

`enable_ssh_keygen: true`

`ssh_public_key: "ssh-ed25519 KEY FROM ANSIBLE SETUP>`

`ssh_public_key: "ssh-ed25519 KEY FROM NEW LAPTOP>`

adding it to the custom.yml file as such. It did not work. Is there another way to do it?

**Comment by notthebee** [comment]
As of now, you can only add one SSH public key

**Comment by notthebee** [comment]
bump

**Comment by notthebee** [comment]
Hi @trashdad 

You should theoretically be able to add multiple keys like this:
```
ssh_public_key: |
    ssh-ed25519 key1
    ssh-ed25519 key2
```

Let me know if that helps

**Comment by notthebee** [comment]
Closing as 'fixed'. Let me know if this doesn't work.
