### ISSUE TITLE
Internal Server Error 500 on AWS EC2

### ISSUE THREAD

**Issue by in2gee** [notthebee/ansible-easy-vpn#71]
Problem with login to Authelia just right after install. Leading to bunkerweb's Internal Server Error 500 screen.

Ubuntu 20.04 LTS on AWS EC2
No email setup.

_docker logs authelia_
```
...
time="2022-09-26T17:18:48Z" level=info msg="Initializing server for non-TLS connections on '[::]:9091' path '/'"
time="2022-09-26T17:23:11Z" level=debug msg="Check authorization of subject username= groups= ip=xxx.xxx.xxx.xxx and object https://wg.*.duckdns.org/ (method )."
time="2022-09-26T17:23:11Z" level=info msg="Access to https://wg.*.duckdns.org/ (method unknown) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=xxx.xxx.xxx.xxx
```

_docker logs bunkerweb_
```
...
2022/09/26 17:18:58 [notice] 57#57: [INIT] Init phase ended
2022/09/26 17:18:58 [notice] 57#57: using the "epoll" event method
2022/09/26 17:18:58 [notice] 57#57: nginx/1.20.2
2022/09/26 17:18:58 [notice] 57#57: built by gcc 10.3.1 20210424 (Alpine 10.3.1_git20210424)
2022/09/26 17:18:58 [notice] 57#57: OS: Linux 5.15.0-1020-aws
2022/09/26 17:18:58 [notice] 57#57: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2022/09/26 17:18:58 [notice] 57#57: start worker processes
2022/09/26 17:18:58 [notice] 57#57: start worker process 60
2022/09/26 17:18:58 [notice] 57#57: start worker process 61
wg.*.duckdns.org xxx.xxx.xxx.xxx - - [26/Sep/2022:17:23:11 +0000] "GET / HTTP/2.0" 302 138 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"
2022/09/26 17:23:12 [error] 60#60: *29 lua entry thread aborted: runtime error: /opt/bunkerweb/core/whitelist/whitelist.lua:129: attempt to concatenate local 'err' (a nil value)
stack traceback:
coroutine 0:
        /opt/bunkerweb/core/whitelist/whitelist.lua: in function 'access'
        access_by_lua(access-lua.conf:63):36: in main chunk, client: xxx.xxx.xxx.xxx, server: auth.*.duckdns.org, request: "GET /?rd=https%3A%2F%2Fwg.***.duckdns.org/ HTTP/2.0", host: "auth.*.duckdns.org"
auth.*.duckdns.org xxx.xxx.xxx.xxx - - [26/Sep/2022:17:23:12 +0000] "GET /?rd=https%3A%2F%2Fwg.*.duckdns.org/ HTTP/2.0" 500 8527 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:105.0) Gecko/20100101 Firefox/105.0"
```

_docker exec -it bunkerweb /bin/sh_

According to /opt/bunkerweb/core/whitelist/whitelist.lua near 129 line
it is something about checking "if rDNS is in whitelist"

But "attempt to concatenate local 'err' (a nil value)" looks like a script bug.
Idk. Not familiar with Lua nor with Bunkerweb

_p.s. bunkerweb.io site is down rn with "Internal Server Error 500"
idk if it's related_

**Comment by in2gee** [comment]
_At last i had some time to play with this issue._

Considering absence of  confirmation, it's for sure turned out that the issue is rather local . 
I've tried to setup using other ISP and it went without a problem.
Using other devices from the main ISP also leading to the problem.

So it seems Bunkerweb doesn't like my ip or ISP, or something else (maybe router). 

What I was trying to do to solve the problem.
Because of this:
`[error] 60#60: *29 lua entry thread aborted: runtime error: /opt/bunkerweb/core/whitelist/whitelist.lua:129: attempt to concatenate local 'err' (a nil value)
stack traceback:
coroutine 0:
        /opt/bunkerweb/core/whitelist/whitelist.lua: in function 'access'`
I just stupidly add **USE_WHITELIST=no** to _$HOME/ansible-easy-vpn/roles/bunkerweb/templates/env.j2_ config file.
This gives me almost identical thing but with blacklist insted of whitelist.
Something like this:
`[error] ... lua entry thread aborted: runtime error: /opt/bunkerweb/core/blacklist/blacklist.lua:129: attempt to concatenate local 'err' (a nil value)
stack traceback:
coroutine 0:
        /opt/bunkerweb/core/blacklist/blacklist.lua: in function 'access'`
Even the line number of the script containing error remains the same.

Now adding the **USE_WHITELIST=no** and **USE_BLACKLIST=no** to env.j2 _solves the problem_.

This workaround isn't really acceptable so I ask if any suggestions for better solutions?


Footnote/
Still don't really clear to me why scripts crushing (leading to server error 500) instead of some kind of handling with returning 403 or something...
129 line of the scripts sits in the section of checking rDNS.

nslookup to my ip (actually to ip of my ISP linked to me) return nothing. But should it?
Maybe Bunkerweb need for some decent host to be returned to allow connection?

**Comment by notthebee** [comment]
nslookup only works with domain names as far as I know

This looks like a bunkerweb bug, so it would probably be a good idea to report it here: https://github.com/bunkerity/bunkerweb/issues

**Comment by in2gee** [comment]
Actually you can use nslookup to (reverse) lookup of a domain name from an ip address. Almost like host (or dig with -x key...) 
Anyways, I just wanted to say that for example if i do lookup to my ip, it doesn't find any .in-addr.arpa PTR records, but if I do lookup to ip of my second ISP it returns the pointer to something like 4-3-2-1.goodisp.net. It means my second isp has own domain for each public ip which is linked to users. Right? So at first I thought Bunkerweb configured like this to do all this rDNS lookups for each user as some kind of check and I just wanted to find how to turn it off. Actually all these rdns stuff is pretty wierd.. so most likely I'm probably just missing something.

Funny thing that bunkerweb.io is mostly return same 500 error for me while docs.bunkerweb.io works fine.
