### ISSUE TITLE
hello, i ran into some problems 

### ISSUE THREAD

**Issue by forestsounds89** [notthebee/ansible-easy-vpn#73]
i got this error:
Would you like to run the playbook now? [y/N]: y
Vault password: 
ERROR! We were unable to read either as JSON nor YAML, these are the errors we got from each:
JSON: Expecting value: line 1 column 1 (char 0)

Syntax Error while loading YAML.
  did not find expected key

The error appears to be in '/root/ansible-easy-vpn/secret.yml': line 1, column 19, but may
be elsewhere in the file depending on the exact syntax problem.

another attempt i got this error after entering my domain name:
Running certbot in dry-run mode to test the validity of the domain...
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Waiting for verification...
Cleaning up challenges
An unexpected error occurred:
The server experienced an internal error :: Error finalizing order :: Unable to meet CA SCT embedding requirements
Please see the logfiles in /var/log/letsencrypt for more details

i choose the kvm host from your video, there is a system upgrade to 22.04.1 available 
also im not using duckDNS i used dynu ddnsgeek.com adress

**Comment by medanthelinium** [comment]
Seems like a temporary issue with Let's Encrypt. Try again

**Comment by forestsounds89** [comment]
i actually combined 3 of your vpn videos to reach what i wanted thank you very much for all of your work excellent content in every way, i used the new videos suggested cheap vps, i used the instructions from the first video and then used the script from the wireguard video, in the end i have a cheap wireguard vps in a country of my choosing and following your steps i have locked it down to the best of my abilities as of now but im still learning, looking forward to more security and privacy related content 
i will probably try this method again soon
