### ISSUE TITLE
What's the easiest way to customize the playbook?

### ISSUE THREAD

**Issue by hungry-bogart** [notthebee/ansible-easy-vpn#74]
I ran the playbook the other day and a couple things didn't work for me. I have a total of 5 users accessing this account and I didn't really need to set up any of the ssh elements. They already grabbed their own keys prior to this.

The port number we use is non-standard and unassigned, so it seemed that something in the playbook set it back to port 22.

I guess this is not an issue technically, but I wasn't sure where to ask this. Thanks for the help.

**Comment by hungry-bogart** [comment]
Ok. I found that  under /roles/ssh/tasks/ there is a config for sshd. I will go ahead and close this, but feel free to add any helpful tips here. For anyone else reading this you may want to look in similar areas as roles appears to contain many other files related to the playbook.

**Comment by notthebee** [comment]
Also take a look here: https://github.com/notthebee/ansible-easy-vpn/blob/main/inventory.yml#L51
