### ISSUE TITLE
wg-quick up

### ISSUE THREAD

**Issue by dynimighti** [notthebee/ansible-easy-vpn#77]
downloaded a script from https://github.com/max-moser/network-manager-wireguard to set up gui in ubuntu, install worked but the vpn does not. i have no interest in small networking cli stuff so i kind of hate that linux wants me to understand before i use this stuff (i just want a vpn that works). what info in the config file do i need to setup correctly.

**Comment by dynimighti** [comment]
i used your scriped and a racknerd server which i bought, that worked for windows at first but now it is being naughty. i am really not that technical, just followed the youtube instructions ( should say i did do the first vpn and that works better than wireguard but can only have one connection at a time and it is really slow, still i like it better becasue it...works). as an aside, got another vpn on AWS through Openvpn but same issue with only allowing one connection at a time. tried to get wireguard working with cli instrurctions on a few linux virtual machines i run, did not really understand the wireguard help because i did not do all the server side certifications so it ended up that i had to purge wireguard then get new network connections...blah...blah...blah. had  i hardly know what i did.

**Comment by notthebee** [comment]
You can leave anything at default, the public key should be in the [Peer] section of the config file

**Comment by dynimighti** [comment]
where is the public key, i avoid using scp because it never works for me but now i don't know whre the key is on the server?

**Comment by dynimighti** [comment]
reinstalled to ubuntu 22, not working: wireguard says active but no internet connection. not sure what is wrong, should say i have a windows app that works as a vpn but i do not like the  that i do not control all the setttings. if i change the vps to debian will that help?

**Comment by notthebee** [comment]
I'm not sure what you mean with "i have a windows app that works as a vpn".
Are you using the official Wireguard client?

**Comment by dynimighti** [comment]
https://myaccount.openvpn.com/as/login
