### ISSUE TITLE
Install failing even after Redeploy

### ISSUE THREAD

**Issue by digidude512** [notthebee/ansible-easy-vpn#80]
VPN: Virmach
Distro: Ubuntu 20.04 Minimal Latest

ASK [system : Update and upgrade apt packages] *************************************************************
fatal: [localhost]: FAILED! => changed=false 
  msg: '''/usr/bin/aptitude safe-upgrade'' failed: '
  rc: -9
  stdout: |-
    Reading package lists...
    Building dependency tree...
    Reading state information...
    Initializing package states...
    Writing extended state information...
    Building tag database...
    No packages will be installed, upgraded, or removed.
    0 packages upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    Need to get 0 B of archives. After unpacking 0 B will be used.
    Writing extended state information...
  stdout_lines: <omitted>

PLAY RECAP **************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by notthebee** [comment]
Cannot reproduce on the latest Ubuntu 20.04 running on Hetzner:
https://github.com/notthebee/ansible-easy-vpn/actions/runs/3409248790/jobs/5670778067#step:15:8483
```
TASK [system : Update and upgrade apt packages] ********************************
ok: [localhost]
```
