### ISSUE TITLE
Secure dns with Wireguard

### ISSUE THREAD

**Issue by yusyel** [notthebee/ansible-easy-vpn#81]
This is not an issue actually. I was looking solution for secure dns with wireguard(for me iphone with nextdns  & doh) and I found this solution: https://help.nextdns.io/t/83hna6p/guide-nextdns-mullvad-wireguard-doh3-on-ios-ipados-macos

Maybe it's good idea add this on github page Q&A.

Fantastic work btw. Recently installed debian 11 and worked like champ.

**Comment by notthebee** [comment]
Sort of implemented in [97da769](https://github.com/notthebee/ansible-easy-vpn/commit/97da7694b56b09172aca9c8b9f0732f0ecaa5cad) via AdGuard, Unbound and DNSCrypt-Proxy.

Follow the instructions here to add the functionality to your currently running VPN: https://github.com/notthebee/ansible-easy-vpn/issues/66#issuecomment-1321851071
