### ISSUE TITLE
Running on a Local server behind a router

### ISSUE THREAD

**Issue by orionbg** [notthebee/ansible-easy-vpn#83]
Hey,
I would like to use the VPN server on a machine I have at home.
I do have a router and the machine is connected to it.
I was wondering if this install would work for that setup and if yes, which ports do I need to redirect on the router to get everything to work properly?
I'll be running Ubuntu 22.04 LTS on the system.
My idea is for several outside devices to connect to the internet through this VPN.

**Comment by notthebee** [comment]
In order to make the VPN work behind NAT, you need to forward the ports 80, 443 and 51820
