### ISSUE TITLE
Every time I try to Install, I get this error... Ubuntu 22.04

### ISSUE THREAD

**Issue by orionbg** [notthebee/ansible-easy-vpn#85]
TASK [ssh : Update SSH configuration to be more secure] ************************
failed: [localhost] (item={'regexp': '^#?PasswordAuthentication', 'line': 'PasswordAuthentication no'}) => changed=false 
  ansible_loop_var: item
  item:
    line: PasswordAuthentication no
    regexp: ^#?PasswordAuthentication
  msg: Destination /etc/ssh/sshd_config does not exist !
  rc: 257
failed: [localhost] (item={'regexp': '^#?PermitRootLogin', 'line': 'PermitRootLogin no'}) => changed=false 
  ansible_loop_var: item
  item:
    line: PermitRootLogin no
    regexp: ^#?PermitRootLogin
  msg: Destination /etc/ssh/sshd_config does not exist !
  rc: 257
failed: [localhost] (item={'regexp': '^#?Port', 'line': 'Port 22'}) => changed=false 
  ansible_loop_var: item
  item:
    line: Port 22
    regexp: ^#?Port
  msg: Destination /etc/ssh/sshd_config does not exist !
  rc: 257
failed: [localhost] (item={'regexp': '^#?PermitEmptyPasswords', 'line': 'PermitEmptyPasswords no'}) => changed=false 
  ansible_loop_var: item
  item:
    line: PermitEmptyPasswords no
    regexp: ^#?PermitEmptyPasswords
  msg: Destination /etc/ssh/sshd_config does not exist !
  rc: 257
failed: [localhost] (item={'regexp': '^#?X11Forwarding', 'line': 'X11Forwarding no'}) => changed=false 
  ansible_loop_var: item
  item:
    line: X11Forwarding no
    regexp: ^#?X11Forwarding
  msg: Destination /etc/ssh/sshd_config does not exist !
  rc: 257

RUNNING HANDLER [Restart authelia] *********************************************

PLAY RECAP *********************************************************************
localhost                  : ok=47   changed=9    unreachable=0    failed=1    skipped=14   rescued=0    ignored=0

**Comment by notthebee** [comment]
What VPS are you running this on?

**Comment by orionbg** [comment]
It is not a VPS. Just a normal PC, running Ubuntu 22.04
Clean install of Ubuntu.

**Comment by notthebee** [comment]
On a desktop version of Ubuntu, the SSH server might not be installed by default. This playbook is made to run on Ubuntu **Server**.

If you want to use your desktop computer as a VPN server to have access to your home network on the go, you will also have to port forward the ports 80, 443 and 51820 on your router, and most likely need to set up dynamic DNS.

**Comment by orionbg** [comment]
You are correct, I am using the desktop version of Ubuntu 22.04 LTS
I have already forwarded the ports, and also set the DDNS from DuckDNS.
Can I install this SSH server? Sorry if asking obvious things but my experience with linux is quite limited.

**Comment by orionbg** [comment]
New update. I installed the openssh server and the install went to the end with the commands for getting the SSH key.
The problem now is that when I execute command 1 for connecting to the SSH it asks for the root password and after I enter it, it says Permission Denied, please try again. (i checked my root password, it is correct)
Ideas? :)

**Comment by orionbg** [comment]
New update 2: I  did enable the root user login in the SSH config and restarted the service. Now I get Permission Denied (publickey)...

**Comment by notthebee** [comment]
If you'll be administrating your Ubuntu box from the desktop, you don't really need SSH access

**Comment by orionbg** [comment]
OK. I pressed enter and the install completed.
Then I went to the web interface to login and it asks for the 2 factor authentication.
How to get the link if I'm not SSH connected to the machine? I tried to just open a terminal and write show_2fa but it says Command not found

**Comment by notthebee** [comment]
Have you reqeusted a link "via e-mail", as shown in the video?

If you did, and it still doesn't work – are you using bash?
If not, open a new shell with bash and type `source .bashrc && show_2fa`

**Comment by orionbg** [comment]
I'm using the default terminal in Ubuntu. It seems to be bash
I tried the command and still getting the same "Command not found" for show_2fa

**Comment by notthebee** [comment]
Hmm.. Try the command directly without the alias: `sudo cat /opt/docker/authelia/notification.txt`

**Comment by orionbg** [comment]
ok, that worked.
I was not automatically redirected to the Wireguard interface after that for some reason but I wrote the URL and I'm in.
Hopefully, everything will work now. Thanks for all the help!

**Comment by notthebee** [comment]
No problem.
