### ISSUE TITLE
HELP! I don't know how to install this on aws 

### ISSUE THREAD

**Issue by Loading9487** [notthebee/ansible-easy-vpn#86]
I am using an aws free tier server, i've reached the point where it says enter domain name, but it gets stuck on http-01 challenge for (my domain here), ive tried using cloudflare and duck dns but both does the same thing, stuck on the challenge. Im not very good with servers (please excuse me lol) Thanks!

**Comment by notthebee** [comment]
You need to allow ports 443/tcp, 80/tcp, 69/tcp and 51820/udp in the security group of your EC2 instance.
