### ISSUE TITLE
Ubuntu Server as Client

### ISSUE THREAD

**Issue by Dinodanio** [notthebee/ansible-easy-vpn#87]
I followed your guide and i have a VPN running on an external server. 
My local laptop and iphone connects fine, but my local ubuntu server can not do the handshake. 

What i have done so far:

1. I created a client config on the VPN host in the Wireguard GUI
2. I downloaded this config to extract the values
3. I create a key pair on my local server
4. I configured the connection
5. I temporally enabled the logs in the linux kernel module to verify that something happen
6. I see `***: Invalid handshake initiation from *****`

Do you have any ideas what i am doing wrong?

**Comment by notthebee** [comment]
You don't need to manually create a key pair on the client. Just download the config, place it into `/etc/wireguard/client.conf` and execute `wg-quick client`

**Comment by Dinodanio** [comment]
God damn i am stupid... Thank you!
