### ISSUE TITLE
without domain

### ISSUE THREAD

**Issue by arsaces7** [notthebee/ansible-easy-vpn#88]
is it possible to put my vps ip addresse instead of domain?
its just more realible to connect directly to server ip 
i get many dns error while connecting and beacause of that i changed it to server ip in wireaguard config

**Comment by arsaces7** [comment]
thank you for answering
another question , can i change the port in custom file right now ? doesn't break anything?

**Comment by notthebee** [comment]
Yes, just re-run the playbook after changing the port
