### ISSUE TITLE
dnscrypt&unbound customization

### ISSUE THREAD

**Issue by MossNotFound** [notthebee/ansible-easy-vpn#93]
how do i "officially" configure dnscrypt and unbound settings without having it potentially be overwritten in the future?

**Comment by notthebee** [comment]
Hi,

For now, the only thing that can be configured 'officially' is upstream DNS – you have a choice between Cloudflare, Google and Quad9.

If you want to use your own config files, the relevant files in the project are:
https://github.com/notthebee/ansible-easy-vpn/blob/main/roles/dns/files/adguard-unbound/files/unbound/unbound.conf
https://github.com/notthebee/ansible-easy-vpn/blob/main/roles/dns/templates/dnscrypt-proxy.toml.j2

**Comment by MossNotFound** [comment]
Thank you for the fast response!

I assume that after fidgeting with those two files i have run this afterward right?
`ansible-playbook run.yml`

**Comment by notthebee** [comment]
Yep, at least with `--tags dns`

**Comment by MossNotFound** [comment]
Ah i got this error while running the script

> ERROR! the role 'chriswayg.msmtp-mailer' was not found in /home/wireshark/ansible-easy-vpn/roles:/home/wireshark/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/wireshark/ansible-easy-vpn
The error appears to be in '/home/wireshark/ansible-easy-vpn/run.yml': line 54, column 7, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
    - role: chriswayg.msmtp-mailer
      ^ here

**Comment by MossNotFound** [comment]
can i just delete the whole block of it for now as i dont use email?

**Comment by notthebee** [comment]
You need to install Ansible Galaxy dependencies first:

```
cd $HOME/ansible-easy-vpn
ansible-galaxy install -r requirements.unless
```

**Comment by MossNotFound** [comment]
ohh woops i tried removing it and marched forward and got this

> RUNNING HANDLER [dns : Restart adguard-unbound-doh] ****************************
fatal: [localhost]: FAILED! => changed=false
  msg: 'value of state must be one of: absent, present, started, stopped, got: restarted'

but internet still seems to be working so hopefully nothing broke as i retry again

**Comment by notthebee** [comment]
That's my bad. It should finish fine the 2nd time, but pull the latest version of the repo for future changes.

You'll also need to restart the container manually: `docker restart adguard-unbound-doh`

**Comment by MossNotFound** [comment]
okay yup everything is up and working in order now!
you're a godsent for this awesome project! manually setting up unbound+dnscrypt is a pain.
