### ISSUE TITLE
No such file directory when trying to test 

### ISSUE THREAD

**Issue by FGARCIA25** [notthebee/ansible-easy-vpn#97]
Hello, 
When trying to follow step 2 which is copying and pasting the command to a new powershell, after typing my pass, it states no such file or directory. Please assist.

**Comment by notthebee** [comment]
Have you checked the last question in the FAQ?

**Comment by FGARCIA25** [comment]
I have. Dir has been made. When running the second command, it states "Permission denied (publickey)"

**Comment by FGARCIA25** [comment]
Would it make sense to run the cmd again in powershell ?

**Comment by FGARCIA25** [comment]
Hello, please advise ??

**Comment by notthebee** [comment]
Not much I can do without a Windows system to test. The script does work on Linux and people have made it work on Windows

**Comment by notthebee** [comment]
I've been able to Windows and confirm that the commands work on Windows as long as you remove `~/` before `.ssh`. Like this:

```
scp -P 22 root@65.109.141.154:/tmp/id_ssh_ed25519 ~/.ssh/id_vpn_username
ssh -p 22 username@65.109.141.154 -i ~/.ssh/id_vpn_username
```

**Comment by FGARCIA25** [comment]
I'm getting the following error .... "Permission denied (publickey)."

**Comment by notthebee** [comment]
In that case you didn't set up the VPS correctly. Please reset your machine and try again.

**Comment by FGARCIA25** [comment]
When you state "reset" are you saying to re-install windows again ?

**Comment by Gasconyman** [comment]
Hello notthebee, thank you for your amazing script and your hard work. I also have the same problem mentioned by FGARCIA. I have purchased the VPS from some website and it has Ubuntu 20 installed on it. I don't know much about linux. Things seem to work fine until the part where I need to open a new terminal to create a SSH key. It just shows an error saying "No such file or directory"

**Comment by notthebee** [comment]
I was not able to reproduce the issue on Powershell and Windows. Please make sure you follow the instructions carefully and read the `Q: I can't copy the SSH key to my Windows machine` part in the FAQ

**Comment by Gasconyman** [comment]
I have checked the FAQ and have tried to follow the steps as carefully as I could. I guess there might be something different about our VPS's setup that is preventing the script from working correctly. Still thanks man.
