### ISSUE TITLE
Error: Problem binding to port 80: Could not bind to IPv4 or IPv6

### ISSUE THREAD

**Issue by AbhayGhante** [notthebee/ansible-easy-vpn#99]
Got This Error after adding doamin; Installing on VPS; Debian 10 may be & Nginx is already installed on port 80
Please tell way to fix this! Like installing this vpn on different port

**Comment by notthebee** [comment]
This playbook will not work if there's already a web server installed on the machine, since it sets up its own web server (bunkerized-nginx)
